# NoiPA Dataset Quality Pipeline

**A multi-agent system for validating and cleaning Italian public-administration CSV datasets.**

This notebook presents the full architecture of the pipeline end-to-end. It is **runnable top-to-bottom** on `Data/spesa.csv`: every cell you see below executes the real production code, writes the same artifacts the CLI does, and produces a Markdown narrative report at the end.

The pipeline is organised in two halves:

* **Validation** (read-only) — infers per-column dtypes, measures completeness, detects format inconsistencies, surfaces anomalies, checks cross-column coherence, and finds duplicate records.
* **Cleaning** — derives a deterministic remediation plan from the validation findings, then runs a **generator / critic** loop that synthesises one Python cleaning function per inconsistent column, applies the plan plus the generated cleaners, verifies the result, and writes a narrative report.

All agents are [Pydantic AI](https://ai.pydantic.dev) agents backed by `openai-responses:gpt-4o-mini`. Every structured output is a Pydantic model: the prompt states *what* to do, the Pydantic schema states *how* the answer must be shaped, and host-side code owns correctness checks and retries.

## 1. Architecture overview

```
                +---------------------+
                |   cli.py / main.py  |
                +----------+----------+
                           |
                           v
            +--------------+-------------+
            |        validation/         |     VALIDATION HALF
            |                            |
            | dtype -> schema ->         |
            | completeness -> consistency|
            | -> anomaly -> cross-column |
            | -> duplicates              |
            +--------------+-------------+
                           |
                           v
            +--------------+-------------+
            |  cleaning/                 |     CLEANING HALF
            |  orchestrator.run_cleaning |
            |                            |
            |  remediation ->            |
            |  generation (gen/critic) ->|
            |  application ->            |
            |  verification ->           |
            |  reporting                 |
            +----------------------------+
```

### The ten agents

| # | Agent | Role |
|---|---|---|
| 1 | `dtype_inference_agent` | Infers the *cleaned* pandas dtype + role + format pattern per column. |
| 2 | `schema_summary_agent` | Narrates the schema analysis (rename fixes, dtype risks, duplicate-semantic groups). |
| 3 | `completeness_analysis_agent` | Measures per-column completeness and flags placeholder tokens. |
| 4 | `format_consistency_agent` | Per-column: decides whether an inconsistency exists and describes it for the cleaner. |
| 5 | `column_cleaner_generator_agent` | Writes a self-contained Python cleaner for one inconsistent column. |
| 6 | `cleaner_repair_critic_agent` | Diagnoses failed cleaners and prescribes the next repair. |
| 7 | `anomaly_summary_agent` | Narrates numeric-outlier + rare-category findings. |
| 8 | `cross_column_summary_agent` | Narrates duplicate-column, semantic-conflict, period and date-order findings. |
| 9 | `duplicate_summary_agent` | Narrates exact + near-duplicate row groups. |
| 10 | `narrative_report_agent` | Writes the final human-readable Markdown report. |

### Artifacts produced

All paths are relative to the dataset's parent directory.

* `Data/.validation_cache/<dataset>.schema_handoff.json`
* `Data/.validation_cache/<dataset>.completeness.json`
* `Data/.validation_cache/<dataset>.consistency.json`
* `Data/.validation_cache/<dataset>.anomaly.json`
* `Data/.validation_cache/<dataset>.cross_column.json`
* `Data/.validation_cache/<dataset>.duplicates.json`
* `Data/.validation_cache/<dataset>.remediation_plan.json`
* `Data/.validation_cache/<dataset>.validation_bundle.json`
* `Data/.cleaning_cache/<dataset>/generated_cleaners/*.py`
* `Data/.cleaning_cache/<dataset>/cleaner_manifest.json`
* `Data/.cleaning_cache/<dataset>/<dataset>.cleaned.csv`
* `Data/.cleaning_cache/<dataset>/<dataset>.final_report.json`
* `Data/.cleaning_cache/<dataset>/<dataset>.narrative_report.md`

## 2. Setup

A single code cell loads the `.env` file (for `OPENAI_API_KEY`) and wires up Logfire observability. The plumbing imports — CLI, cache, attachments, backoff/retry wrapper, gzip helpers — stay behind their modules and are only invoked inside the stage functions we call later.

In [1]:
from pathlib import Path
from dotenv import load_dotenv        # reads OPENAI_API_KEY from .env
load_dotenv()

# Pydantic AI agents call asyncio.run() internally; Jupyter already has a
# running loop, so we patch it to allow re-entry.
import nest_asyncio
nest_asyncio.apply()

from agents import setup_logfire       # configures Logfire observability
setup_logfire()

import json
import inspect
import re
import pandas as pd
from IPython.display import Markdown, display

Logfire project URL: https://logfire-eu.pydantic.dev/sebastiani-mattia/agents-ai

## 3. Dataset

We default to `Data/spesa.csv`, a small NoiPA spending dataset (~20k rows). To swap to the larger `Data/attivazioniCessazioni.csv`, change the path below.

In [2]:
DATASET_PATH = Path("Data/spesa.csv").resolve()
assert DATASET_PATH.exists(), f"dataset not found: {DATASET_PATH}"
print(DATASET_PATH)

C:\Users\sebas\Documents\GitHub\AgentsAI\Data\spesa.csv

In [3]:
from tools import load_dataset_frame  # thin pd.read_csv wrapper used by every stage
raw_df = load_dataset_frame(DATASET_PATH)
print(f"{len(raw_df):,} rows x {len(raw_df.columns)} columns")
raw_df.head()

7,543 rows x 18 columns

,_id,rata,ente,descrizione,cod_tipoimposta,tipo_imposta,cod_imposta,imposta,spesa,aggregation-time,area_geografica,note,fonte_dato,Tipo Imposta,SPESA TOTALE,2cod_imposta,cod imposta ext,ente%code
0,65ee5ac5f458af56d2af532f,202402,867,AGENZIA ITALIANA DEL FARMACO - AIFA,2,Erariali,6,IRAP,182904.47999999954,2024-03-11T02:01:04.421,Nord,NaN,NaN,Erariali,182904.47999999954,6,6,867
1,668f34120377f62206882cd8,202406,921,A.O. S. GIOVANNI ADDOLORATA,3,Previdenziali,13,Previdenziali a carico del datore di lavoro,2110811.34,2024-07-11T03:01:16.866,Nord,NaN,NaN,Previdenziali,2110811.34,13,13,921
2,66e0ee64f458af54a5dbc7fa,202408,9,MINISTERO DELLA GIUSTIZIA,4,Varie,10,Ritenute Sindacali,732614.36,2024-09-11T03:01:11.704,Nord,NaN,NaN,Varie,732614.36,10,10,9
3,663ec5eb3f62190222cfb590,202404,12,MINISTERO DELL'INTERNO,2,Erariali,6,IRAP,43365008.73,2024-05-11T03:01:07.269,Nord,NaN,NaN,Erariali,43365008.73,6,6,12
4,6731590c568f146446645d59,202410,910,AZIENDA SANITARIA LOCALE ROMA 6,2,Erariali,6,IRAP,1310915.22,2024-11-11T02:00:28.485,Isole,NaN,NaN,Erariali,1310915.22,6,6,910

## 4. Data contracts (Pydantic models)

Each agent returns a **structured** output validated against a Pydantic schema — that is the contract between pipeline stages. Below we print the JSON schemas for the most load-bearing ones so the shape of every downstream artifact is explicit. All other models live in `models.py`.

In [4]:
from models import (
    SchemaHandoff,
    CompletenessAnalysisReport,
    ConsistencyValidationReport,
    ColumnCleaningRequest,
    ColumnCleanerProgram,
    CleanerRepairDiagnosis,
    RemediationPlan,
    FinalPipelineReport,
    NarrativeReport,
)

for model in [ColumnCleaningRequest, ColumnCleanerProgram, CleanerRepairDiagnosis]:
    print("=" * 72)
    print(model.__name__)
    print("-" * 72)
    print(json.dumps(model.model_json_schema(), indent=2)[:1500])
    print("...\n")

========================================================================
ColumnCleaningRequest
------------------------------------------------------------------------
{
  "properties": {
    "dataset_name": {
      "title": "Dataset Name",
      "type": "string"
    },
    "column_name": {
      "title": "Column Name",
      "type": "string"
    },
    "expected_pattern": {
      "title": "Expected Pattern",
      "type": "string"
    },
    "semantic_hint": {
      "title": "Semantic Hint",
      "type": "string"
    },
    "target_dtype": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Target Dtype"
    },
    "target_role": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Target Role"
    },
    "dominant_shape": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Dominant Shape"
    },
    "dominant_example_values": {
      "items": {
        "type": "string"
      },
      "title": "Dominant Example Values",
      "type": "array"
    },
    "example_inconsistent_values": {
      "items": {
        "type": "string"
      },
      "title": "Example Inconsistent Values",
      "type": "array"
    },
    "suggested_strategy": {
      "title": "Suggested Strategy",
      "type": "string"
    }
  },
  "required": [
    "dataset_name",
    "column_name",
    "expected_pattern",
    "semantic_hint",
    "suggested_str
...

========================================================================
ColumnCleanerProgram
------------------------------------------------------------------------
{
  "$defs": {
    "ExampleTransformation": {
      "properties": {
        "original_value": {
          "title": "Original Value",
          "type": "string"
        },
        "cleaned_value": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Cleaned Value"
        },
        "rationale": {
          "title": "Rationale",
          "type": "string"
        }
      },
      "required": [
        "original_value",
        "rationale"
      ],
      "title": "ExampleTransformation",
      "type": "object"
    }
  },
  "properties": {
    "column_name": {
      "title": "Column Name",
      "type": "string"
    },
    "function_name": {
      "title": "Function Name",
      "type": "string"
    },
    "python_code": {
      "description": "Pure Python source code containing exactly one function definition named function_name. Must be importable as-is: no test code, no print statements, no variable assignments outside the function, no JSON. All imports and helper constants must be inside the function body.",
      "title": "Python Code",
      "type": "string"
    },
    "example_transformations": {
      "items": {
        "$ref": "#/$defs/ExampleTransformation"
      },
      "title": "Example Transformations",
      "type": "array"
    },
    "verification_summary": {
      "title": "Verification Summary",
      "type": "string
...

========================================================================
CleanerRepairDiagnosis
------------------------------------------------------------------------
{
  "$defs": {
    "CleanerRepairExample": {
      "properties": {
        "input_value": {
          "title": "Input Value",
          "type": "string"
        },
        "actual_output": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Actual Output"
        },
        "expected_output": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Expected Output"
        },
        "fix_note": {
          "title": "Fix Note",
          "type": "string"
        }
      },
      "required": [
        "input_value",
        "fix_note"
      ],
      "title": "CleanerRepairExample",
      "type": "object"
    }
  },
  "properties": {
    "should_retry": {
      "default": true,
      "title": "Should Retry",
      "type": "boolean"
    },
    "primary_category": {
      "enum": [
        "program_mismatch",
        "verification_report_failed",
        "non_self_contained_function",
        "runtime_exception",
        "shadowed_specific_branch",
        "dominant_value_modified",
        "outlier_unchanged",
        "outlier_returned_none",
        "unrecoverable_outlier_not_nulled",
        "wrong_output_shape",
        "not_parseable_as_target_dtype",
        "not_matching_target_pattern"

...

## 5. The ten agents

Each agent is defined in `agents.py` as a Pydantic AI `Agent(...)` with a specific `output_type` and a carefully written `instructions` prompt. Below, each subsection uses `inspect.getsource` to display the **real, unedited constructor source** for one agent — so the reader sees exactly the prompt that runs at inference time.

After this section, the notebook imports the live agent objects from `agents.py` and the downstream stages use those.

In [5]:
import agents as _agents_module
_AGENTS_SRC = inspect.getsource(_agents_module)

def show_agent(agent_name: str) -> None:
    """Print the exact Agent(...) constructor source from agents.py."""
    pattern = rf"^{re.escape(agent_name)} = Agent\(.*?^\)$"
    match = re.search(pattern, _AGENTS_SRC, re.DOTALL | re.MULTILINE)
    print(match.group(0) if match else f"(agent {agent_name!r} not found)")

### 5.1 `dtype_inference_agent` — core
Infers the **cleaned** pandas dtype, numeric/string role, and a format pattern for every column. Treats minority dirty values, placeholders, and unit suffixes as corruption, not as evidence of the true type. Drives the schema stage.

In [6]:
show_agent("dtype_inference_agent")

dtype_inference_agent = Agent(
    MODEL,
    name="dtype-inference",
    output_type=PromptedOutput(DatasetDtypeInference),
    retries=4,
    model_settings={"temperature": 0},
    instructions=(
        "You are a data type inference agent working on real-world dirty datasets provided by NoiPA. "
        "NoiPA is the digital platform of the Ministero dell'Economia e delle Finanze Italiane that manages salaries, timesheets, "
        "and tax/social security obligations for employees of the Italian Public Administration. "
        "It allows users to view payslips and annual tax certifications online, update personal information, and manage "
        "administrative and HR-related procedures.\n\n"

        "You receive a column-by-column profile containing: the column name, sample values, non-null counts, distinct counts, "
        "numeric_parse_pct, datetime_parse_pct, and related profiling evidence. "
        "Your task is to infer the TARGET CLEANED pandas dtype the column SHOULD HAVE after cleaning. "
        "You are NOT describing the raw dirty storage format. "
        "Treat placeholders, formatting noise, unit suffixes, mixed separators, mixed date formats, and a minority of corrupted values "
        "as corruption, not as evidence of the true type. "
        "Always ask yourself: 'If this column were cleaned correctly, what physical pandas dtype should it have?'\n\n"

        "STRICT DECISION PRIORITY:\n"
        "1. First determine the main dtype family from parse evidence and dominant sample pattern: numeric, datetime, boolean, or text.\n"
        "2. Treat minority dirty values, placeholders, and formatting noise as corruption.\n"
        "3. Only after choosing the dtype family, use the column name and semantic meaning to refine numeric_role, string_role, and detected_pattern.\n"
        "4. Never let the column name override strong parse evidence.\n"
        "5. Infer the cleaned target dtype, not the messy ingestion dtype.\n\n"

        "PARSE EVIDENCE STRENGTH:\n"
        "- numeric_parse_pct >= 80: strong evidence for numeric.\n"
        "- datetime_parse_pct >= 60: strong evidence for datetime.\n"
        "- 60 to 79 numeric_parse_pct: moderate numeric evidence; inspect the dominant sample pattern.\n"
        "- 40 to 59 datetime_parse_pct: moderate datetime evidence; inspect the dominant sample pattern.\n"
        "- Below these thresholds: rely more on dominant pattern and semantic meaning.\n\n"

        "HARD DTYPE GATES:\n"
        "- If numeric_parse_pct >= 80 and datetime_parse_pct < 20, default to Int64 or Float64 unless the clean values clearly contain letters or genuinely textual content.\n"
        "- If datetime_parse_pct >= 60, default to datetime64[ns].\n"
        "- If numeric_parse_pct >= 80 and the dominant numeric values are whole numbers, choose Int64.\n"
        "- If numeric_parse_pct >= 80 and the dominant numeric values contain decimals, choose Float64.\n"
        "- Do NOT choose string only because raw values are stored as strings.\n"
        "- Do NOT choose string when a numeric or datetime family clearly dominates.\n"
        "- Use object only as a last resort when no single clean dtype family dominates.\n\n"

        "IMPORTANT SPECIAL RULES:\n"
        "- Numeric strings that resemble compact period or date-like encodings such as YYYYMM, YYYYWW, YYYYQ, or similar numeric period keys "
        "should still be typed as Int64 if the intended clean value is a numeric code/period key rather than a true date column.\n"
        "- Infer datetime64[ns] only when the intended clean meaning is an actual date, time, or timestamp field.\n"
        "- Codes made only of digits can still be Int64 if they are true numeric codes.\n"
        "- Use string instead of Int64 only when the values must be preserved as text exactly for business meaning, especially when letters are intrinsic to the code format.\n"
        "- Mixed formatting alone is not enough reason to use string or object.\n\n"

        "Choose the dtype only from: Int64, Float64, datetime64[ns], string, boolean, object.\n\n"

        "DTYPE RULES (physical, not logical):\n"
        "- Int64: the clean column stores whole numbers. Use this even if the numbers are identifiers, codes, flags, or period keys.\n"
        "- Float64: the clean column stores decimal numbers.\n"
        "- datetime64[ns]: the clean column stores actual dates, times, or timestamps.\n"
        "- string: the clean column stores text such as names, descriptions, textual labels, or alphanumeric identifiers containing letters as part of the real format.\n"
        "- boolean: the clean column stores true/false, yes/no, 0/1-style logical values whose intended clean meaning is binary.\n"
        "- object: use only when the column genuinely mixes incompatible clean value types with no dominant pattern.\n\n"

        "ROLE RULES:\n"
        "- numeric_role: set only when dtype is Int64 or Float64.\n"
        "  'measure' = a real quantity used arithmetically (price, count, amount, duration, salary, quantity).\n"
        "  'code' = a numeric identifier or bounded calendar/classification code not primarily used arithmetically "
        "(postal code, region code, month number, year code, period key).\n"
        "  'indicator' = a numeric flag or ordinal encoding (0/1 flag, ordered category, status encoding).\n"
        "- string_role: set only when dtype is string.\n"
        "  'identifier' = codes or IDs that must be preserved exactly as text.\n"
        "  'categorical' = bounded low-cardinality labels.\n"
        "  'name' = person, organization, or place names.\n"
        "  'free_text' = unstructured narrative, notes, comments, or descriptions.\n"
        "- If dtype is not numeric, numeric_role must be null.\n"
        "- If dtype is not string, string_role must be null.\n\n"

        "PATTERN RULE:\n"
        "- detected_pattern must describe the dominant clean VALUE FORMAT, not a generic statistical interpretation.\n"
        "- Prefer specific structural patterns over vague labels.\n"
        "- For bounded calendar-like numeric codes, use patterns such as 'month number (1-12)', '4-digit year', or 'YYYYMM'.\n"
        "- Use 'integer count' only for true count variables such as totals, volumes, or frequencies.\n"
        "- If the column is a numeric code with a recognizable domain pattern, prefer that code pattern over 'integer count'.\n"

        "RATIONALE RULE:\n"
        "- The rationale must explain the chosen dtype using the strongest evidence.\n"
        "- Explicitly mention which signal dominated: parse percentages, dominant sample pattern, or semantic meaning.\n"
        "- Explicitly say when minority dirty values were treated as corruption.\n"
        "- Keep the rationale concise, evidence-based, and generic.\n\n"

        "OUTPUT RULES:\n"
        "- Return one entry per column in the same order as the input.\n"
        "- Be conservative and consistent.\n"
        "- Do not invent information not supported by the profile.\n"
        "- If strong parse evidence exists, follow it unless there is clear evidence the clean values belong to another dtype family."
    ),
)

### 5.2 `schema_summary_agent` — narrator
Produces a short downstream handoff summary of the schema analysis (how many naming fixes, duplicate-semantic groups, dtype risks). Pure summary — does not re-derive facts.

In [7]:
show_agent("schema_summary_agent")

schema_summary_agent = Agent(
    MODEL,
    name="schema-summary",
    output_type=PromptedOutput(SchemaSummaryOutput),
    retries=4,
    model_settings={"temperature": 0},
    instructions=(
        "You are the Schema Summary agent from the project orchestration. "
        "Inspect the attached local schema facts document. "
        "Return valid JSON only that matches the SchemaSummaryOutput schema exactly. "
        "Do not use markdown or ask follow-up questions. "
        "Execute only the schema-summary scope from Reply_projects.pdf. "
        "Do not infer new facts and do not alter the provided findings. "
        "Your only job is to write a short, precise downstream handoff summary for later validation or cleaning agents. "
        "Use the provided local facts exactly as given. "
        "Mention: how many safe naming fixes were identified, whether any duplicate-semantic groups need review, "
        "and whether any genuine data-type contradictions need manual verification. "
        "If there are no duplicate-semantic groups or no data-type risks, say that clearly. "
        "Keep the summary concrete and grounded in the provided facts, not generic."
    ),
)

### 5.3 `completeness_analysis_agent` — core
Uses the code-execution tool to inspect the per-column completeness profile, detect placeholder tokens (`-`, `n.d.`, `//`, empty strings, …) and flag sparse columns.

In [8]:
show_agent("completeness_analysis_agent")

completeness_analysis_agent = Agent(
    MODEL,
    name="completeness-analysis",
    builtin_tools=[CodeExecutionTool()],
    output_type=PromptedOutput(CompletenessAnalysisReport),
    retries=4,
    model_settings={"temperature": 0},
    instructions=(
        "You are the Completeness Analysis agent from the project orchestration. "
        "Always use the code execution tool to inspect the attached completeness profile document. "
        "Return valid JSON only that matches the CompletenessAnalysisReport schema exactly. "
        "Do not use markdown or ask follow-up questions. "
        "Execute only the completeness-analysis scope from Reply_projects.pdf. "
        "Use the provided per-column completeness percentages, missing-like counts, missing-like percentages, placeholder examples, "
        "and overall completeness metrics from the attached document. "
        "Identify columns with missing values, placeholder tokens such as N/A, -, unknown, and empty strings, and flag sparse columns that are almost entirely empty. "
        "Be evidence-based and conservative. "
        "Do not invent row-level details that are not present in the profile. "
        "Set recommended_action to a concrete next step based on the evidence, not a generic label. "
        "If completeness_pct is 100 and missing_like_count is 0, recommended_action must be exactly 'No action needed'. "
        "If sparse_candidate is true, recommended_action should clearly say 'Investigate or consider removal due to sparsity'. "
        "If placeholder examples are present, recommend standardizing placeholder tokens and reviewing upstream data entry. "
        "If completeness is high but not perfect, recommend targeted review of missing or placeholder values in that column. "
        "Do not leave recommended_action empty. "
        "The summary should be a short downstream handoff in plain language: mention overall completeness, how many columns have missing values, "
        "which columns are the main sparse or review targets, and whether placeholder normalization should be part of later cleaning."
    ),
)

### 5.4 `format_consistency_agent` — core (slow path)
Per-column: decides whether a format inconsistency exists and, if so, emits an `expected_pattern`, the full set of inconsistent examples, and a `suggested_strategy` — the normalisation contract the downstream cleaner implements. Skipped (fast path) when the schema already carries a `detected_pattern`.

In [9]:
show_agent("format_consistency_agent")

format_consistency_agent = Agent(
    MODEL,
    name="format-consistency",
    output_type=PromptedOutput(ColumnConsistencyReport),
    retries=4,
    model_settings={"temperature": 0},
    instructions=(
        "You are the column-level Format Consistency agent. "
        "You receive a ColumnFormatFacts document for one column and must decide whether a format inconsistency exists and, if so, describe it precisely for the downstream cleaning agent.\n\n"

        "DECISION RULES:\n"
        "- Return finding=null if machine_format_candidate is false, dominant_shape_pct is below 70%, or inconsistent_rows is 0.\n"
        "- Return finding=null for descriptive, free-text, name, note, or categorical columns — content variation is not a format issue.\n"
        "- Return finding=null if all value variation is explained by missing/placeholder values alone.\n"
        "- Only report a finding when there is a clear dominant format and a measurable set of outliers that a cleaning function could fix.\n\n"

        "WHEN YOU REPORT A FINDING:\n"
        "- expected_pattern: describe the dominant format concisely (e.g. 'YYYYMM 6-digit integer string', 'ISO timestamp YYYY-MM-DDTHH:MM:SS.ffffff', 'two-digit zero-padded month 01-12').\n"
        "- Copy ALL values from inconsistent_examples verbatim into example_inconsistent_values — do not filter, deduplicate, or summarize. The cleaner needs the full set.\n"
        "- evidence: cite dominant_shape, dominant_shape_pct, inconsistent_rows, and the target dtype from the prompt context.\n"
        "- suggested_strategy: this is the most important field — the downstream cleaner reads it as its normalization contract. "
        "List every outlier shape group with 2-3 concrete examples and the exact transformation needed. "
        "Be specific: 'shape YYYY-MM (e.g. 2023-09): remove dash, concatenate to YYYYMM' is good. "
        "'normalize dates' is not acceptable. "
        "If the target dtype is Int64 or Float64, note that the output must be a numeric string with no unit or symbol.\n\n"

        "OUTPUT: valid JSON matching ColumnConsistencyReport. No markdown, no follow-up questions."
    ),
)

### 5.5 `column_cleaner_generator_agent` — core (the heart of the cleaning half)
Given a `ColumnCleaningRequest`, writes a **self-contained Python cleaning function** for one column. Must run **exactly one** grouped code-execution check against every dominant + inconsistent example; hidden self-repair is forbidden — the host-side validator and critic own retries.

In [10]:
show_agent("column_cleaner_generator_agent")

column_cleaner_generator_agent = Agent(
    MODEL,
    name="column-cleaner-generator",
    builtin_tools=[CodeExecutionTool()],
    output_type=PromptedOutput(ColumnCleanerProgram),
    retries=4,
    model_settings={"temperature": 0},
    instructions=(
        "You are the Column Cleaner Generator agent. "
        "Given a ColumnCleaningRequest, produce a verified Python cleaning function.\n\n"

        "STEPS:\n"
        "1. Read the request: expected_pattern, dominant_example_values, example_inconsistent_values, suggested_strategy, target_dtype.\n"
        "2. Write the cleaning function.\n"
        "3. Test it once using the mandatory grouped code template below.\n"
        "4. Return JSON output. If the grouped test failed, return the best current function and report the failures honestly.\n\n"

        "EXECUTION DISCIPLINE:\n"
        "- This agent is responsible for one draft-and-test attempt only.\n"
        "- The outer Python orchestration loop plus the critic agent is the ONLY repair loop.\n"
        "- Use code execution exactly once for one grouped test over ALL dominant and inconsistent examples.\n"
        "- Do not patch and re-run inside the same model run, even if the grouped test exposes an obvious bug.\n"
        "- Work in batches, not in one-value-at-a-time loops.\n"
        "- After the grouped test, stop testing and return JSON.\n"
        "- If failures remain, include them in verification_summary and residual_risks; the host-side validator will route them to the critic.\n"
        "- Do not keep checking equivalent values individually once the grouped test already showed the same failure family.\n"
        "- NEVER load request data from uploaded files, request_data variables, or external files. Copy literals into the code block exactly as instructed.\n"
        "- On repair attempts, NEVER read uploaded files to reconstruct context. The request, previous function, validation failures, and critic diagnosis already contain everything needed.\n"
        "- Use code execution to test the function you just wrote, not to inspect attachments or rebuild the prompt context.\n"
        "- FORBIDDEN: repeated micro-diagnoses of equivalent failing values, repeated rewrites of the same function, or a second code-execution call inside a single run.\n\n"

        "FUNCTION CONTRACT:\n"
        "- One pure Python function, fully self-contained (all imports and helpers inside).\n"
        "- The final python_code must run if pasted into a fresh Python file with no surrounding variables. Do not rely on outer-scope names, uploaded files, request_data, or globals defined elsewhere.\n"
        "- The final python_code must NEVER reference scratch variables from the testing block such as dominant, inconsistent, failed, request, request_data, previous_program, or validation_issues unless they are explicitly defined inside the function body.\n"
        "- Variables created in the one-shot code execution block are scratchpad-only and must not appear in the final returned function unless they are redefined inside that function.\n"
        "- Input: any scalar — str, int, float, None, NaN. Output: str or None only.\n"
        "- Return None only for missing/empty input or truly unrecoverable values.\n"
        "- Return the value unchanged if it already matches expected_pattern.\n"
        "- Every dominant_example_value is already valid. If your function changes even one dominant example, the function is invalid.\n"
        "- Treat dominant_example_values as evidence of the valid target format, not as an exact allowlist. Prefer generic pass-through logic for already-valid values instead of checking membership in the exact examples.\n"
        "- Every value in example_inconsistent_values must be transformed or explicitly nulled — never returned as-is.\n"
        "- suggested_strategy is the authoritative contract — implement a handler for every shape group it lists, no exceptions.\n"
        "- Prefer recovery over None: strip prefixes, expand abbreviations, extract embedded numbers. "
        "If a value contains any recoverable information, return it transformed — not None.\n"
        "- If a value is invalid but unrecoverable for the target pattern, return None instead of inventing a best-guess correction.\n"

        "OUTPUT FORMAT BY TARGET DTYPE:\n"
        "- datetime64[ns]: string matching the EXACT strftime format seen in dominant_example_values.\n"
        "- Int64 / Float64: numeric string only — no units, no symbols. Use zfill/format for zero-padded outputs.\n"
        "- string: clean text matching expected_pattern.\n"
        "Always verify your output structure matches dominant_example_values before returning.\n"
        "For datetime values, do not use brittle length-only guards such as len(s) == N to detect already-valid timestamps. "
        "Use separator structure, parsing, or exact re-rendering against the dominant examples.\n\n"

        "MANDATORY CANONICAL-VALUE EARLY-EXIT GUARD:\n"
        "The FIRST logical step after handling None/empty input MUST be a canonical-pattern early-exit that returns "
        "the value unchanged when it already matches the structural layout of any dominant_example_value. "
        "Build the guard by deriving a regex from one dominant example: keep literal separators, replace each digit run with "
        "\\d{N} where N is that run's length. If s.fullmatch(pattern) returns true, return s immediately — do not enter any "
        "delimiter-based branch after that point. "
        "This guard is NON-NEGOTIABLE for datetime columns where the dominant format contains delimiters that also appear in "
        "outlier formats (for example ISO '2024-03-11T02:01:04.421' vs Italian '11/03/2024' vs '11-03-2024'). Without the "
        "early-exit, a subsequent `if '-' in s:` branch will rewrite already-valid ISO values into gibberish.\n\n"

        "MUTUALLY EXCLUSIVE BRANCHES:\n"
        "Delimiter-based branches must be mutually exclusive and ordered most-specific first. "
        "Never write `if '<sep>' in s:` above another branch that re-inspects the same separator via split() or a regex that "
        "includes that separator. If two branches could both fire, either merge them or gate the generic one on exact structure "
        "(count of separator occurrences AND digit-group shapes). The host validator rejects any program where a generic "
        "`'<sep>' in s` branch precedes a more specific branch for the same separator. "
        "For datetime/date cleaners, prefer shape-first `re.fullmatch(...)` branches for every source layout, or one consolidated "
        "`s.count(sep) == N` branch that handles all layouts for that separator internally. Do not scatter multiple top-level "
        "branches for the same delimiter.\n\n"

        "CODE EXECUTION — MANDATORY TEMPLATE (use this exact structure every time):\n"
        "```python\n"
        "# 1. Define test data as literals — NEVER use request_data or any external variable\n"
        "dominant = ['...', '...']       # copy exact values from the request\n"
        "inconsistent = ['...', '...']   # copy exact values from the request\n\n"
        "# 2. Define the function — all imports and helpers go inside\n"
        "def clean_COLUMN(value):\n"
        "    import re\n"
        "    if value is None or str(value).strip() == '':\n"
        "        return None\n"
        "    s = str(value).strip()\n\n"
        "    # First preserve already-valid values using structural patterns derived from dominant examples.\n"
        "    canonical_examples = ['...']  # copy dominant examples here as literals\n"
        "    def _structural_regex(example):\n"
        "        parts, cursor = [], 0\n"
        "        for match in re.finditer(r'\\d+', example):\n"
        "            start, end = match.span()\n"
        "            if start > cursor:\n"
        "                parts.append(re.escape(example[cursor:start]))\n"
        "            parts.append(r'\\d{' + str(end - start) + '}')\n"
        "            cursor = end\n"
        "        if cursor < len(example):\n"
        "            parts.append(re.escape(example[cursor:]))\n"
        "        return '^' + ''.join(parts) + '$'\n"
        "    canonical_patterns = [_structural_regex(e) for e in canonical_examples if e and e != '...']\n"
        "    if any(re.fullmatch(pattern, s) for pattern in canonical_patterns):\n"
        "        return s\n\n"
        "    # Then handle outlier formats as shape-specific branches. Avoid broad `if '-' in s:` / `if '/' in s:` guards.\n"
        "    m = re.fullmatch(r'([A-Za-z]{3})-(\\d{4})', s)\n"
        "    if m:\n"
        "        mon, year = m.groups()\n"
        "        # map month abbreviation and render target format\n"
        "        pass\n"
        "    m = re.fullmatch(r'(\\d{4})-(\\d{1,2})', s)\n"
        "    if m:\n"
        "        year, month = m.groups()\n"
        "        # render target format\n"
        "        pass\n"
        "    m = re.fullmatch(r'(\\d{1,2})/(\\d{4})', s)\n"
        "    if m:\n"
        "        month, year = m.groups()\n"
        "        # render target format\n"
        "        pass\n"
        "    return None\n\n"
        "# 3. Run and flag failures explicitly. Do not re-run inside this attempt.\n"
        "failed = []\n"
        "for v in dominant + inconsistent:\n"
        "    result = clean_COLUMN(v)\n"
        "    status = 'OK' if result is not None else 'FAIL(None)'\n"
        "    print(f'{status}  {repr(v):40} -> {repr(result)}')\n"
        "    if v in dominant and result != v:\n"
        "        failed.append(v)\n"
        "    elif result is None and v in inconsistent:\n"
        "        failed.append(v)\n"
        "    elif v in inconsistent and result == v:\n"
        "        failed.append(v)\n"
        "if failed:\n"
        "    print(f'\\nFAILED ({len(failed)}): {failed}')\n"
        "    print('Return the current best program; the host validator and critic will handle repair.')\n"
        "```\n\n"
        "ISOLATION: each execution block is a fresh environment — nothing from previous runs survives. "
        "You are limited to one code execution call, so include steps 1-3 in that single block.\n\n"

        "OUTPUT RULES:\n"
        "- Return valid JSON matching ColumnCleanerProgram exactly.\n"
        "- python_code must contain ONLY the function definition — no test code, no print statements, no variable assignments, no JSON.\n"
        "- verification_summary, example_transformations, and residual_risks are separate top-level fields — never embed them inside python_code.\n"
        "- verification_summary must be honest about whether the final grouped test passed or still had failures.\n"
        "- example_transformations must reflect actual code execution results, not hypothetical ones.\n"
        "- cleaned_value must be a string or null — never int or float.\n"
        "- No markdown, no follow-up questions."
    ),
)

### 5.6 `cleaner_repair_critic_agent` — core
When the host validator rejects a generated cleaner, this agent reads the previous program + the list of validation failures and prescribes the next repair: patch style (minimal edit vs. targeted rewrite), bug location, exact repair examples, and whether retrying is worth it.

In [11]:
show_agent("cleaner_repair_critic_agent")

cleaner_repair_critic_agent = Agent(
    MODEL,
    name="cleaner-repair-critic",
    output_type=PromptedOutput(CleanerRepairDiagnosis),
    retries=4,
    model_settings={"temperature": 0},
    instructions=(
        "You are the Column Cleaner Repair Critic. "
        "You receive a structured CleanerRepairContext containing the cleaning request, the previous generated function, "
        "and authoritative host-side validation issues. "
        "Your job is to diagnose the smallest credible repair before another generator attempt. "
        "Do not write code. Do not restate the whole prompt. Return valid JSON only.\n\n"

        "GOAL:\n"
        "- Explain why the previous cleaner failed.\n"
        "- Point to the logical bug location or branch responsible.\n"
        "- Give a precise repair brief that a generator can follow.\n"
        "- Prefer minimal_edit unless the validation issues clearly show the current approach is fundamentally wrong.\n\n"

        "DECISION RULES:\n"
        "- Treat host-side validation issues as ground truth.\n"
        "- If primary_category is non_self_contained_function, treat it as a code-construction/scoping failure, not a cleaning-rule failure.\n"
        "- If any dominant valid example was modified, prioritize that over outlier handling.\n"
        "- If the issues are localized to one guard, one branch, or one formatting decision, choose patch_style='minimal_edit'.\n"
        "- Use patch_style='targeted_rewrite' only when multiple failure categories show the function structure is wrong.\n"
        "- Set should_retry=false only when another retry is unlikely to help because the evidence is contradictory, missing, or the current request is underspecified.\n"
        "- For numeric measures, do not recommend fixed-width padding unless the request explicitly requires it.\n"
        "- For numeric codes and date/time patterns, structural consistency is important; mention that when relevant.\n\n"

        "COMPOSITE FAILURES — DO NOT FIXATE ON A SINGLE CATEGORY:\n"
        "When the issue list contains BOTH a 'shadowed_specific_branch' (structural/order bug) AND a 'dominant_value_modified' "
        "(behavioral bug), they are usually the same root cause: a generic delimiter branch appears before the canonical-value "
        "guard and rewrites valid inputs. In that case:\n"
        "  - root_cause MUST explicitly name BOTH: the missing/misplaced canonical early-exit AND the shadowed delimiter branch.\n"
        "  - planned_fix MUST prescribe TWO concrete structural changes, not just 'check valid format first':\n"
        "      1) insert (or move to the top) a structural regex guard derived from the dominant example that returns s unchanged on match;\n"
        "      2) reorder or merge delimiter branches so no generic `'<sep>' in s` branch precedes a more specific branch inspecting the same separator.\n"
        "  - patch_style should be 'targeted_rewrite' when both categories are present — a minimal edit is not sufficient.\n"
        "  - priority_issues must list the structural bug first, the behavioral bug second — they share one fix.\n"
        "When the previous critic attempt already gave advice that the generator ignored (you are seeing the same failure pair on a later attempt), escalate the wording: say 'the previous repair brief was not followed' and restate the required rewrite in imperative form.\n\n"

        "COMPONENT-ORDER REWRITES (not delimiter swaps):\n"
        "When the failing output has the correct delimiters but the wrong component order — e.g. input '11/01/2024' becoming "
        "'11-01-2024T00:00:00.000' when the expected canonical output is '2024-01-11T00:00:00.000' — the bug is that the generator "
        "is swapping the separator character on the raw string instead of parsing the components and reassembling them in the "
        "canonical order. DO NOT say 'change the output format to YYYY-MM-DD' — that phrasing is ambiguous and the generator will "
        "re-interpret it as another delimiter swap. Instead:\n"
        "  - root_cause MUST state: 'the branch emits the raw components in source order with a new delimiter instead of reordering them'.\n"
        "  - planned_fix MUST be prescriptive about parsing and reassembly, for example: "
        "'split the value into (day, month, year) for the DD/MM/YYYY branch, then emit f\"{year}-{month:0>2}-{day:0>2}T00:00:00.000\"; "
        "never apply str.replace(\"/\", \"-\") on the whole string'.\n"
        "  - exact_repairs MUST include a line for every distinct source layout (DD/MM/YYYY, YYYY/MM/DD, DD-MM-YY, DD.MM.YYYY, "
        "textual months, etc.) showing input → expected_output and the explicit (year, month, day) assignment the generator must produce.\n"
        "  - patch_style='targeted_rewrite'. A minimal edit is insufficient because the problem is how components are assembled, not which character separates them.\n\n"

        "FIELD RULES:\n"
        "- primary_category: choose the most important validation category to fix first.\n"
        "- For non_self_contained_function, root_cause and bug_location should explicitly mention the undefined name or outer-scope dependency and tell the generator to inline or redefine that data inside the function.\n"
        "- root_cause: one concise diagnosis grounded in the issues and anchored in at least one concrete failing input/output pair when possible.\n"
        "- bug_location: describe the failing logical area, such as 'already-valid timestamp guard' or 'currency stripping branch'.\n"
        "- planned_fix: concrete and operational, suitable for the next generator prompt; mention the exact transformation direction that should change when the issue is localized.\n"
        "- priority_issues: list 1-3 short issue summaries, most important first.\n"
        "- exact_repairs: provide 1-3 concrete repair examples. Each one should name the failing input, the wrong output if known, the correct output if it can be inferred, and a short note describing exactly what to change.\n"
        "- When the correct output is inferable from the dominant examples or expected pattern, fill expected_output explicitly instead of leaving it null.\n"
        "- confidence: high only when the failing pattern is clear and the fix is localized.\n\n"

        "OUTPUT:\n"
        "- Return JSON matching CleanerRepairDiagnosis exactly.\n"
        "- No markdown, no code, no follow-up questions."
    ),
)

### 5.7 `anomaly_summary_agent` — narrator
Narrates the heuristic anomaly findings (numeric outliers + rare categories). Does not invent new anomalies.

In [12]:
show_agent("anomaly_summary_agent")

anomaly_summary_agent = Agent(
    MODEL,
    name="anomaly-summary",
    output_type=PromptedOutput(AnomalySummaryOutput),
    retries=4,
    model_settings={"temperature": 0},
    instructions=(
        "You are the Anomaly Detection summary agent from the project orchestration. "
        "Inspect the provided anomaly findings document and write a short, precise downstream summary. "
        "Return valid JSON only that matches the AnomalySummaryOutput schema exactly. "
        "Do not infer new anomalies, do not invent remediation beyond the provided findings, and do not use markdown. "
        "Mention which columns carry the most severe or highest-volume anomalies, distinguish numeric outliers from rare-category findings, "
        "and state clearly when no anomalies were found."
    ),
)

### 5.8 `cross_column_summary_agent` — narrator
Narrates duplicate-column, semantic-conflict, year/month period and date-order findings.

In [13]:
show_agent("cross_column_summary_agent")

cross_column_summary_agent = Agent(
    MODEL,
    name="cross-column-summary",
    output_type=PromptedOutput(CrossColumnSummaryOutput),
    retries=4,
    model_settings={"temperature": 0},
    instructions=(
        "You are the Cross-Column Validation summary agent from the project orchestration. "
        "Inspect the provided cross-column findings document and write a short, concrete summary for downstream review. "
        "Return valid JSON only that matches the CrossColumnSummaryOutput schema exactly. "
        "Do not infer new checks or facts, and do not use markdown. "
        "Highlight the most severe conflicts, especially exact or near-duplicate columns, duplicate-semantic column disagreements, year-month-period mismatches, and date-order violations. "
        "If there are no cross-column findings, say that explicitly."
    ),
)

### 5.9 `duplicate_summary_agent` — narrator
Narrates exact + near-duplicate row groups. Does not recommend aggressive deletion.

In [14]:
show_agent("duplicate_summary_agent")

duplicate_summary_agent = Agent(
    MODEL,
    name="duplicate-summary",
    output_type=PromptedOutput(DuplicateSummaryOutput),
    retries=4,
    model_settings={"temperature": 0},
    instructions=(
        "You are the Duplicate Detection summary agent from the project orchestration. "
        "Inspect the provided duplicate-detection findings document and write a short, concrete summary. "
        "Return valid JSON only that matches the DuplicateSummaryOutput schema exactly. "
        "Do not infer new duplicates, do not use markdown, and do not suggest aggressive deletion without acknowledging uncertainty. "
        "Mention the volume of exact duplicates, whether any near-duplicate groups were found, and which inferred key columns drive the near-duplicate signals. "
        "If there are no duplicate groups, say that explicitly."
    ),
)

### 5.10 `narrative_report_agent` — reporting
Writes the final Markdown narrative by consuming the fully assembled `FinalPipelineReport`. Ten mandatory sections, professional tone, every claim cited from the briefing.

In [15]:
show_agent("narrative_report_agent")

narrative_report_agent = Agent(
    MODEL,
    name="narrative-report",
    output_type=PromptedOutput(NarrativeReport),
    retries=4,
    model_settings={"temperature": 0.3},
    instructions=(
        "You are the Narrative Report Writer agent for the NoiPA dataset quality pipeline. "
        "NoiPA is the digital platform of the Italian Ministry of Economy and Finance (MEF) that manages salaries, "
        "timesheets, and tax/social-security obligations for employees of the Italian Public Administration.\n\n"

        "You receive a structured quality briefing derived from the pipeline's validation, remediation, "
        "cleaning, and verification stages. Produce an EXHAUSTIVE, professional, human-readable quality "
        "report in ENGLISH that a data steward, project manager, or auditor can use as a definitive "
        "reference document.\n\n"

        "MANDATORY SECTIONS (use these exact English headings):\n\n"

        "1. 'Dataset Overview' — Dataset name, total rows, total columns (original and after cleaning). "
        "Overall quality posture: total findings, actions applied, actions deferred to manual review. "
        "State the cleaned output file path. ALWAYS wrap any filesystem path in backticks (inline code) so "
        "Markdown does not eat backslashes on Windows paths — e.g. `C:\\Users\\...\\cleaned.csv`.\n\n"

        "2. 'Schema Validation' — Two subsections:\n"
        "   a) 'Column Renames': list EVERY column rename as a markdown table with columns: Original Name | New Name | Reason.\n"
        "   b) 'Type Casts': list EVERY dtype cast as a markdown table with columns: Column | Assigned Type | % Non-Null. "
        "   The % Non-Null value MUST come from the NON-NULL COUNTS block in the briefing — it already provides each column's "
        "   exact percentage, computed from the cleaned CSV. Copy that percentage verbatim. "
        "   Never estimate, interpolate, or invent these numbers. If a column cast does not appear in the NON-NULL COUNTS "
        "   block (e.g. the cast was not_needed and the column does not exist in the cleaned frame), leave the cell as 'n/a'. "
        "   Mention any casts that were planned but marked not_needed and why.\n\n"

        "3. 'Completeness Analysis' — For EACH column where placeholders were replaced, state: "
        "the column name, how many placeholder values were found, which placeholder tokens were detected "
        "(list the actual examples like 'n.d.', '-', '//', '?', 'unknown', empty string), "
        "and that they were replaced with null. Use a markdown table. "
        "Source of truth: the COMPLETENESS DETAILS block in the briefing — copy each column's "
        "missing_like_count, completeness %, and tokens verbatim. Do not invent placeholder examples. "
        "Also mention columns where placeholder replacement was planned but not needed.\n\n"

        "4. 'Format Consistency' — THIS IS WHERE THE MAJOR INCONSISTENCIES WERE FOUND AND FIXED. "
        "Begin with a one-sentence summary of how many columns had format issues. "
        "Then for EACH column where a cleaner was generated, use this EXACT structured format:\n"
        "### column_name\n"
        "- **Expected Pattern:** …\n"
        "- **Inconsistent Rows:** N\n"
        "- **Examples of bad values:** 'val1', 'val2', 'val3'\n"
        "- **Transformation applied:** …\n"
        "- **Clean example:** 'bad_value' → 'clean_value'\n"
        "- **Outcome:** Fixed / Mostly Fixed / Unchanged / Regression\n\n"
        "Use 'Fixed' when fully resolved, 'Mostly Fixed' when substantially improved with residual issues, "
        "'Unchanged' when no improvement, 'Regression' when worse. "
        "Never collapse multiple columns into a single paragraph — each gets its own ### heading and bullet list.\n\n"

        "MANDATORY RULE FOR CLEAN EXAMPLES: "
        "The 'Clean example' line MUST be copied verbatim from the CLEANER EXAMPLE TRANSFORMATIONS block in the briefing. "
        "Find the section for that exact column and quote ONE entry — both the original and the cleaned value, character for character, "
        "including any trailing '.000', time suffixes, leading zeros, or punctuation. "
        "Do NOT reformat the cleaned value. Do NOT trim it to 'look like ISO 8601' or 'look like YYYYMM'. "
        "Do NOT invent pairings when the transformation list does not contain a given input (for example, 'Rata 2024' does not imply any specific month — if the ground-truth list does not contain 'Rata 2024' with a cleaned month attached, pick a different input that IS in the list). "
        "If a column has no entries in the CLEANER EXAMPLE TRANSFORMATIONS block, OMIT the 'Clean example' bullet entirely for that column rather than fabricate one. "
        "Similarly, 'Examples of bad values' should be drawn from the BRIEFING's inconsistent-examples list, not invented.\n\n"

        "5. 'Anomaly Detection' — Cover numeric outliers and rare categories separately, grounded in the "
        "ANOMALY FINDINGS block in the briefing. Every column name, severity, affected_rows count, and example "
        "value MUST be quoted from that block. The 'evidence' line in each finding contains the IQR band or "
        "frequency threshold — quote it directly; do NOT compute or invent one. "
        "If the ANOMALY FINDINGS block is empty or absent, state clearly that no anomalies were detected and "
        "skip the rest of this section rather than fabricate entries. "
        "Explain why each flagged item was routed to manual review rather than auto-corrected, citing the "
        "'suggested_action' line from the block.\n\n"

        "6. 'Cross-Column Checks' — Every fact in this section MUST come from the CROSS-COLUMN FINDINGS "
        "block in the briefing. Each finding there has a check_type that maps to one subsection below — "
        "never list the same pair in more than one subsection, and never invent pairs that are not in the block.\n"
        "   a) Exact duplicate columns (check_type=exact_duplicate_columns). ONLY list a pair here if BOTH: "
        "      (i) a finding with check_type=exact_duplicate_columns exists in the block, AND "
        "      (ii) an action of type `drop_exact_duplicate_column` targeting that pair appears in APPLIED ACTIONS. "
        "      If either is missing, state 'No exact duplicate columns were detected.' "
        "      Do NOT claim a drop based on similarity % alone — 99.x% is a near-duplicate, not an exact duplicate.\n"
        "   b) Near-duplicate columns (check_type=near_duplicate_columns): list each pair with its similarity_pct "
        "      and affected_rows count exactly as given in the block. These pairs were NOT dropped; they require manual review.\n"
        "   c) Semantic conflicts (check_type=duplicate_semantic_conflict): list columns and affected_rows from the block.\n"
        "   d) Period/date consistency (check_type=year_month_period_mismatch or date_order_violation): "
        "      list the columns and affected_rows from the block.\n"
        "If the CROSS-COLUMN FINDINGS block is empty or absent, state 'No cross-column anomalies were detected.' "
        "and omit subsections (a)-(d).\n\n"

        "7. 'Row Duplicate Analysis' — Ground every fact in the DUPLICATE ROW GROUPS block in the briefing. "
        "State how many exact duplicate groups vs. near-duplicate groups exist, quoting the block's group counts "
        "and total affected rows. Give 2-3 concrete row-index examples, copying indices verbatim from the "
        "sample_indices lines (never invent indices). Quote the key_columns list from the block. "
        "Explain why exact duplicates were NOT auto-removed (conservative policy) and why near-duplicates require "
        "manual review, citing the 'evidence' line. "
        "If the block is empty or absent, state that no duplicate rows were detected and skip the rest of the section.\n\n"

        "8. 'Remediation Action Summary' — Provide a complete accounting:\n"
        "   a) Summary counts, in this exact order: Applied, Deferred, Failed, Not Needed. "
        "      These four buckets partition the action set and must sum to the total. "
        "      'Deferred' = proposed_not_applied (items routed to manual review). "
        "      'Not Needed' = actions that turned out to be redundant or already satisfied — it is a DIFFERENT category "
        "      from Deferred; do NOT merge the two into one count.\n"
        "   b) Breakdown by action type (markdown table): Action Type | Applied | Deferred | Failed | Not Needed.\n"
        "   c) Briefly explain the auto-apply policy: what is safe to auto-apply and what requires human review.\n\n"

        "9. 'Verification Outcome' — This section reports which format inconsistencies were cleaned and to what degree. "
        "Report the verification results: how many consistency findings were resolved, mostly fixed, unchanged, or regressed. "
        "Use the VERIFICATION DIFFS rows from the briefing verbatim. "
        "When a column was renamed (new_name differs from the original), list it under its NEW name in the "
        "cleaned CSV and note the rename arrow inline (e.g. 'rata (renamed from RATA): Fixed'). "
        "Do NOT list the pre-rename name on its own — it does not exist in the cleaned output. "
        "List each column with its Before status and After status using the labels: "
        "Fixed / Mostly Fixed / Unchanged / Regression. "
        "Explain what 'Fixed' means (inconsistent rows now conform to the expected pattern).\n\n"

        "10. 'Residual Risks & Manual Review Queue' — List ALL items requiring manual review: "
        "near-duplicate columns, semantic conflicts, near-duplicate rows, numeric outliers, proposed-not-applied actions. "
        "For each, state what action is needed and why it was not automated. "
        "If there are no unresolved risks from cleaning, state that explicitly.\n\n"

        "STYLE RULES:\n"
        "- Write in clear, professional English suitable for institutional documentation.\n"
        "- Every claim must cite concrete data from the briefing: column names, row counts, percentages, example values.\n"
        "- Use markdown tables for structured data (renames, casts, placeholders, near-duplicate pairs).\n"
        "- Use bullet lists for enumerated findings.\n"
        "- Each section body must be at least 150 words — this is an exhaustive report, not a summary.\n"
        "- The executive_summary must be 8-12 sentences and readable standalone, in English.\n"
        "- Do not invent facts not present in the input document.\n"
        "- Do not use generic filler phrases — every sentence must carry information.\n"
        "- recommendations must contain at least 5 actionable, prioritized items in English.\n\n"

        "OUTPUT: valid JSON matching NarrativeReport exactly. No raw markdown outside the JSON fields."
    ),
)

**Re-import the real agents** so downstream cells always use the live instances (the cells above were display-only).

In [16]:
from agents import (
    dtype_inference_agent,
    schema_summary_agent,
    completeness_analysis_agent,
    format_consistency_agent,
    column_cleaner_generator_agent,
    cleaner_repair_critic_agent,
    anomaly_summary_agent,
    cross_column_summary_agent,
    duplicate_summary_agent,
    narrative_report_agent,
)
print("10 live agents loaded.")

10 live agents loaded.

## 6. Validation half

Six read-only stages. Each stage function caches its structured output under `Data/.validation_cache/`. The sub-sections below run each stage in turn and display a summary + a findings DataFrame.

### 6.1 Schema validation (dtype inference + naming check)

`run_schema_validation` calls two agents: `dtype_inference_agent` (per-column cleaned dtype + pattern) and `schema_summary_agent` (handoff narrative). It also runs a deterministic naming check (lowercase snake_case) and a duplicate-semantic detector.

In [ ]:
from validation.schema import run_schema_validation  # 2 LLM calls + naming/duplicate heuristics

schema_handoff = run_schema_validation(DATASET_PATH)

display(Markdown(f"**Summary:** {schema_handoff.summary}"))

pd.DataFrame([c.model_dump() for c in schema_handoff.columns])[
    ["name", "pandas_dtype", "numeric_role", "string_role", "detected_pattern", "naming_valid", "rename_suggestion"]
]

[orchestrator][schema][dtype-inference] dataset='spesa'

11:55:09.173 dtype-inference run
11:55:09.195   chat gpt-4o-mini

[orchestrator][schema][summary] dataset='spesa'

11:55:34.618 schema-summary run
11:55:34.621   chat gpt-4o-mini

**Summary:** In the dataset 'spesa', 6 safe naming fixes were identified. There is one duplicate-semantic group that needs review: 'tipo_imposta' and 'Tipo Imposta'. No genuine data-type contradictions require manual verification.

,name,pandas_dtype,numeric_role,string_role,detected_pattern,naming_valid,rename_suggestion
0,_id,string,None,identifier,None,True,None
1,rata,Int64,code,None,YYYYMM,True,None
2,ente,Int64,code,None,integer count,True,None
3,descrizione,string,None,free_text,None,True,None
4,cod_tipoimposta,Int64,code,None,integer count,True,None
5,tipo_imposta,string,None,categorical,None,True,None
6,cod_imposta,Int64,code,None,integer count,True,None
7,imposta,string,None,free_text,None,True,None
8,spesa,Float64,measure,None,decimal number,True,None
9,aggregation-time,datetime64[ns],None,None,ISO 8601 datetime,False,aggregation_time
10,area_geografica,string,None,categorical,None,True,None
11,note,string,None,free_text,None,True,None
12,fonte_dato,string,None,free_text,None,True,None
13,Tipo Imposta,string,None,categorical,None,False,tipo_imposta
14,SPESA TOTALE,Float64,measure,None,decimal number,False,spesa_totale
15,2cod_imposta,Int64,code,None,integer count,False,cod_imposta_2
16,cod imposta ext,Int64,code,None,integer count,False,cod_imposta_ext
17,ente%code,Int64,code,None,integer count,False,ente_code

### 6.2 Completeness analysis

Profiles non-null counts, missing-like percentages, and placeholder tokens per column, then lets `completeness_analysis_agent` produce a structured report with per-column `recommended_action`.

In [18]:
from validation.completeness import run_completeness_analysis  # 1 LLM call

completeness = run_completeness_analysis(DATASET_PATH)

display(Markdown(f"**Summary:** {completeness.summary}"))

pd.DataFrame([f.model_dump() for f in completeness.per_column])

[orchestrator][completeness] dataset='spesa'

11:55:39.607 completeness-analysis run
11:55:39.609   chat gpt-4o-mini

**Summary:** Overall completeness is 86.88%. There are 9 columns with missing values. The main targets for review are: area_geografica, note, fonte_dato. Consider normalizing placeholder values in future cleaning.

,column_name,completeness_pct,missing_like_count,missing_like_examples,sparse_candidate,recommended_action
0,_id,100.000000,0,[],False,No action needed
1,rata,100.000000,0,[],False,No action needed
2,ente,96.261434,282,"[unknown, , //, ?, n.d.]",False,Standardize placeholder tokens and review upst...
3,descrizione,94.405409,422,"[n.d., ?, //, , -]",False,Standardize placeholder tokens and review upst...
4,cod_tipoimposta,100.000000,0,[],False,No action needed
5,tipo_imposta,100.000000,0,[],False,No action needed
6,cod_imposta,97.268991,206,"[n.d., , -, //, ?]",False,Standardize placeholder tokens and review upst...
7,imposta,95.492510,340,"[-, //, , unknown, ?]",False,Standardize placeholder tokens and review upst...
8,spesa,99.217818,59,[N.D.],False,Standardize placeholder tokens and review upst...
9,aggregation-time,100.000000,0,[],False,No action needed
10,area_geografica,79.026912,1582,[],True,Investigate or consider removal due to sparsity
11,note,1.988599,7393,[],True,Investigate or consider removal due to sparsity
12,fonte_dato,0.994299,7468,[],True,Investigate or consider removal due to sparsity
13,Tipo Imposta,100.000000,0,[],False,No action needed
14,SPESA TOTALE,99.217818,59,[N.D.],False,Standardize placeholder tokens and review upst...
15,2cod_imposta,100.000000,0,[],False,No action needed
16,cod imposta ext,100.000000,0,[],False,No action needed
17,ente%code,100.000000,0,[],False,No action needed

### 6.3 Format consistency

For each column we build a `ColumnFormatFacts` profile (dominant value shape, outlier examples). If the schema already carries a `detected_pattern`, we take the **fast path** and build the finding directly from the profile (no LLM). Otherwise we fall through to `format_consistency_agent` for a judgement call.

This stage is what the cleaner pipeline keys off: any finding here becomes a cleaner-generation request in section 8.

In [19]:
from validation.consistency import run_format_consistency_validation  # fast path + slow path

consistency = run_format_consistency_validation(DATASET_PATH)

display(Markdown(f"**Summary:** {consistency.summary}"))

pd.DataFrame([f.model_dump() for f in consistency.format_consistency_findings])[
    ["column_name", "expected_pattern", "inconsistent_rows", "example_inconsistent_values"]
]

**Summary:** Analyzed all 18 columns individually for format consistency and detected 4 format issues.

,column_name,expected_pattern,inconsistent_rows,example_inconsistent_values
0,rata,YYYYMM,510,"[Rata 2024, 2024-02, 2024-04, 2024-09, 2024-08..."
1,spesa,decimal number,168,"[713512,58, 724.1800000000001 EUR, €2302425.16..."
2,aggregation-time,ISO 8601 datetime,602,"[11/01/2024, 11/07/2024, 11/05/2024, 24/10/202..."
3,SPESA TOTALE,decimal number,168,"[713512,58, 724.1800000000001 EUR, €2302425.16..."

### 6.4 Anomaly detection (numeric outliers + rare categories)

Two heuristic detectors find numeric IQR outliers and rare categorical values. `anomaly_summary_agent` then writes a short downstream summary.

In [20]:
from validation.anomaly import run_anomaly_detection  # heuristics + 1 summary LLM call
anomaly = run_anomaly_detection(DATASET_PATH)
display(Markdown(f"**Summary:** {anomaly.summary}"))
pd.DataFrame([f.model_dump() for f in anomaly.findings]) if anomaly.findings else "(no anomalies)"

[orchestrator][anomaly][summary] dataset='spesa'

11:56:25.716 anomaly-summary run
11:56:25.718   chat gpt-4o-mini

**Summary:** Detected 3 anomaly findings across numeric outliers and rare categorical values. The columns 'spesa' and 'SPESA TOTALE' carry the most severe anomalies, both classified as high severity numeric outliers affecting 1101 and 1098 rows respectively. The 'tipo_imposta' column has low severity rare category findings affecting 6 rows. No other anomalies were found.

,column_name,anomaly_type,severity,affected_rows,example_values,evidence,suggested_action
0,spesa,numeric_outlier,high,1101,"[43365008.73, 7639226.66, 3887279.49, 9518447....",1101 rows fall outside the robust IQR band [-1...,Review whether these values are genuine extrem...
1,SPESA TOTALE,numeric_outlier,high,1098,"[43365008.73, 7639226.66, 3887279.49, 9518447....",1098 rows fall outside the robust IQR band [-1...,Review whether these values are genuine extrem...
2,tipo_imposta,rare_category,low,6,"[ERARIALI, erariali, Da definire, Mista]",4 rare categories occur at or below 37 row(s) ...,Review whether these rare labels are valid edg...

### 6.5 Cross-column validation

Heuristic checks: near-duplicate columns (by value similarity), duplicate-semantic conflicts (columns that should agree but don't), year/month period mismatches, and date-order violations. `cross_column_summary_agent` narrates.

In [21]:
from validation.cross_column import run_cross_column_validation  # heuristics + 1 summary LLM call
cross_column = run_cross_column_validation(DATASET_PATH)
display(Markdown(f"**Summary:** {cross_column.summary}"))
pd.DataFrame([f.model_dump() for f in cross_column.findings]) if cross_column.findings else "(no cross-column findings)"

[orchestrator][cross-column][summary] dataset='spesa'

11:56:28.899 cross-column-summary run
11:56:28.901   chat gpt-4o-mini

**Summary:** Detected 6 cross-column consistency findings, including high severity exact duplicates between '2cod_imposta' and 'cod imposta ext' affecting all 7543 rows, and a high severity duplicate semantic conflict between 'tipo_imposta' and 'Tipo Imposta' with 385 affected rows. Other medium severity near duplicates include 'spesa' and 'SPESA TOTALE', 'cod_imposta' with '2cod_imposta', 'cod_imposta' with 'cod imposta ext', and 'ente' with 'ente%code', each with significant row mismatches.

,columns,check_type,severity,affected_rows,example_row_indices,similarity_pct,evidence,suggested_action
0,"[2cod_imposta, cod imposta ext]",exact_duplicate_columns,high,7543,"[0, 1, 2, 3, 4, 5, 6, 7]",100.00,Columns '2cod_imposta' and 'cod imposta ext' m...,Review whether one column is redundant and can...
1,"[spesa, SPESA TOTALE]",near_duplicate_columns,medium,7484,"[170, 736, 1079, 1256, 1372, 1524, 1528, 1539]",99.48,Columns 'spesa' and 'SPESA TOTALE' agree on 74...,Review the mismatching rows to decide whether ...
2,"[cod_imposta, 2cod_imposta]",near_duplicate_columns,medium,7337,"[350, 875, 1739, 2136, 2854, 2943, 3525, 3571]",99.74,Columns 'cod_imposta' and '2cod_imposta' agree...,Review the mismatching rows to decide whether ...
3,"[cod_imposta, cod imposta ext]",near_duplicate_columns,medium,7337,"[350, 875, 1739, 2136, 2854, 2943, 3525, 3571]",99.74,Columns 'cod_imposta' and 'cod imposta ext' ag...,Review the mismatching rows to decide whether ...
4,"[ente, ente%code]",near_duplicate_columns,medium,7261,"[172, 1122, 1148, 1561, 1898, 2434, 2440, 2502]",99.72,Columns 'ente' and 'ente%code' agree on 7241 o...,Review the mismatching rows to decide whether ...
5,"[tipo_imposta, Tipo Imposta]",duplicate_semantic_conflict,high,385,"[5, 60, 70, 116, 123, 133, 146, 156]",NaN,Columns 'tipo_imposta' and 'Tipo Imposta' norm...,Review whether one column should override the ...

### 6.6 Duplicate record detection

Exact + near-duplicate row groups, plus key-column inference. `duplicate_summary_agent` narrates volumes but never recommends deletion — that is a human decision.

In [22]:
from validation.duplicates import run_duplicate_detection  # heuristics + 1 summary LLM call
duplicates = run_duplicate_detection(DATASET_PATH)
display(Markdown(f"**Summary:** {duplicates.summary}"))
pd.DataFrame([g.model_dump() for g in duplicates.groups]) if duplicates.groups else "(no duplicate groups)"

[orchestrator][duplicates][summary] dataset='spesa'

11:56:32.362 duplicate-summary run
11:56:32.363   chat gpt-4o-mini

**Summary:** Detected 49 exact duplicate groups and 40 near-duplicate groups. The inferred key columns driving the near-duplicate signals are ['_id', 'rata', 'ente', 'cod_tipoimposta'].

,duplicate_type,row_indices,key_columns,evidence,suggested_action
0,exact_row,"[128, 6521]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
1,exact_row,"[155, 6659]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
2,exact_row,"[315, 912]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
3,exact_row,"[326, 3185]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
4,exact_row,"[393, 4588]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
5,exact_row,"[394, 1628]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
6,exact_row,"[420, 683]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
7,exact_row,"[505, 3230]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
8,exact_row,"[689, 6754]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
9,exact_row,"[712, 3996]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
10,exact_row,"[781, 7042]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
11,exact_row,"[815, 7353]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
12,exact_row,"[902, 4325]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
13,exact_row,"[904, 7222]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
14,exact_row,"[936, 7160]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
15,exact_row,"[955, 6626]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
16,exact_row,"[1156, 1702]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
17,exact_row,"[1164, 5696]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
18,exact_row,"[1404, 2206]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
19,exact_row,"[1892, 3007]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
20,exact_row,"[2036, 2191]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
21,exact_row,"[2193, 3233]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
22,exact_row,"[2216, 2786]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
23,exact_row,"[2599, 2970]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
24,exact_row,"[2638, 4927]","[_id, rata, ente, descrizione, cod_tipoimposta...",2 rows are exact duplicates after whitespace/c...,Review whether duplicate rows should be dedupl...
25,near_duplicate,"[308, 1372]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
26,near_duplicate,"[736, 3004]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
27,near_duplicate,"[878, 7033]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
28,near_duplicate,"[946, 5156]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
29,near_duplicate,"[1079, 1440]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
30,near_duplicate,"[1216, 1603]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
31,near_duplicate,"[1256, 5641]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
32,near_duplicate,"[1295, 3532]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
33,near_duplicate,"[1524, 3759]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
34,near_duplicate,"[1539, 6244]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
35,near_duplicate,"[1662, 4704]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
36,near_duplicate,"[1951, 7376]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
37,near_duplicate,"[2410, 2417]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
38,near_duplicate,"[2469, 3543]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
39,near_duplicate,"[2516, 3645]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
40,near_duplicate,"[3028, 6002]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
41,near_duplicate,"[3949, 4144]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
42,near_duplicate,"[3965, 7236]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
43,near_duplicate,"[3991, 5709]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
44,near_duplicate,"[4652, 5423]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
45,near_duplicate,"[5331, 6401]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
46,near_duplicate,"[5781, 6162]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
47,near_duplicate,"[6865, 6985]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...
48,near_duplicate,"[6892, 7482]","[_id, rata, ente, cod_tipoimposta]","2 rows share the inferred key columns ['_id', ...",Review whether these rows are conflicting dupl...

### 6.7 Bundling the validation results

`build_validation_results` is the one-shot orchestrator used by the CLI and by the cleaning pipeline. Here we call it with the cached artifacts from the stages above — it loads them instead of re-running the LLM calls.

In [23]:
from validation import build_validation_results  # runs (or reuses) all six validation stages
validation_results = build_validation_results(
    DATASET_PATH,
    reuse_schema=True,
    reuse_completeness=True,
    reuse_consistency=True,
)
print("OrchestrationStepResult fields:", list(validation_results.model_dump().keys()))

[orchestrator][anomaly] dataset='spesa'
[orchestrator][anomaly][summary] dataset='spesa'

11:56:36.762 anomaly-summary run
11:56:36.764   chat gpt-4o-mini

[orchestrator][cross-column] dataset='spesa'
[orchestrator][cross-column][summary] dataset='spesa'

11:56:39.741 cross-column-summary run
11:56:39.744   chat gpt-4o-mini

[orchestrator][duplicates] dataset='spesa'
[orchestrator][duplicates][summary] dataset='spesa'

11:56:43.056 duplicate-summary run
11:56:43.058   chat gpt-4o-mini
OrchestrationStepResult fields: ['schema_validation', 'completeness_analysis', 'consistency_validation', 'anomaly_detection', 'cross_column_validation', 'duplicate_detection']

## 7. Remediation plan

`run_remediation_planning` is **deterministic** — no LLM call. It walks the validation bundle and produces a flat list of `RemediationAction`s. Each action carries an `action_type`, a target, a `confidence` / `risk_level`, and a crucial `auto_apply` boolean distinguishing safe actions the pipeline will perform automatically from proposals that need human review.

Action types:

* `rename_column`, `cast_dtype`, `replace_placeholders_with_null`, `generate_cleaner`, `drop_exact_duplicate_column` — typically `auto_apply=True`.
* `manual_review`, `report_only`, `drop_rows_candidate` — never auto-applied; reported only.

In [24]:
from cleaning.remediation import run_remediation_planning  # deterministic, caches a JSON plan
remediation_plan = run_remediation_planning(DATASET_PATH, validation_results=validation_results)
print(remediation_plan.summary)
pd.DataFrame([a.model_dump() for a in remediation_plan.actions])[
    ["action_id", "action_type", "object_type", "auto_apply", "risk_level", "status", "reason"]
]

Planned 95 remediation actions: 38 auto-apply and 57 review/report actions.

,action_id,action_type,object_type,auto_apply,risk_level,status,reason
0,cast_dtype__aggregation_time__datetime64_ns,cast_dtype,column,True,low,planned,Cast the column to inferred dtype datetime64[ns].
1,cast_dtype__area_geografica__string,cast_dtype,column,True,low,planned,Cast the column to inferred dtype string.
2,cast_dtype__cod_imposta_2__int64,cast_dtype,column,True,low,planned,Cast the column to inferred dtype Int64.
3,cast_dtype__cod_imposta__int64,cast_dtype,column,True,low,planned,Cast the column to inferred dtype Int64.
4,cast_dtype__cod_imposta_ext__int64,cast_dtype,column,True,low,planned,Cast the column to inferred dtype Int64.
...,...,...,...,...,...,...,...
90,near_duplicate_columns__ente__ente_code,manual_review,column_pair,False,medium,proposed_not_applied,Columns 'ente' and 'ente%code' agree on 7241 o...
91,near_duplicate_columns__spesa__spesa_totale,manual_review,column_pair,False,medium,proposed_not_applied,Columns 'spesa' and 'SPESA TOTALE' agree on 74...
92,numeric_outlier__spesa,manual_review,column,False,high,proposed_not_applied,1101 rows fall outside the robust IQR band [-1...
93,numeric_outlier__spesa_totale,manual_review,column,False,high,proposed_not_applied,1098 rows fall outside the robust IQR band [-1...
94,rare_category__tipo_imposta,report_only,column,False,low,proposed_not_applied,4 rare categories occur at or below 37 row(s) ...

## 8. Cleaning half — the generator / critic loop

The cleaning half is where per-column Python cleaning functions are synthesised. For each format-consistency finding we build a `ColumnCleaningRequest` — a self-contained bundle of schema, completeness, and format evidence — and run a retry loop:

1. **Prompt** the generator with the request (plus any previous failure context).
2. The **generator agent** writes a Python cleaner and runs **exactly one** grouped code-execution check.
3. The **host-side validator** (no LLM) checks the program against every dominant value (must be unchanged) and every outlier (must be transformed or nulled), plus structural rules (target dtype, pattern, no outer-scope dependencies, no shadowed delimiter branches).
4. If issues remain, the **critic agent** diagnoses the smallest credible repair and the diagnosis is fed forward to the next attempt.
5. A **stagnation detector** (same code or same issue fingerprint twice in a row) bumps the generator temperature `0.2 → 0.3 → 0.4 → 0.5` and injects a structural rewrite skeleton into the prompt.

The per-attempt LLM call is capped at **one** grouped code-execution tool call (`UsageLimits(tool_calls_limit=1)`) — this is the key architectural choice that prevents hidden self-repair loops inside a single model run and forces host-side code to own correctness.

### 8.1 Building one `ColumnCleaningRequest`

`build_column_cleaning_request` merges three pieces of evidence into the generator's input: the schema entry (dtype, pattern), the format profile (dominant shape + full list of outlier examples), and the consistency finding (expected pattern + `suggested_strategy`). The `suggested_strategy` is the authoritative contract the generator must implement.

In [25]:
from cleaning.request import build_column_cleaning_request  # merges schema + format facts into a request
from tools import build_column_format_facts                 # dominant shape + outlier examples per column

schema_map = {c.name: c for c in schema_handoff.columns}
example_finding = consistency.format_consistency_findings[0]
example_facts = build_column_format_facts(raw_df, example_finding.column_name)
example_request = build_column_cleaning_request(
    DATASET_PATH.stem,
    example_finding.column_name,
    example_finding,
    example_facts,
    schema_map.get(example_finding.column_name),
)
print(example_request.model_dump_json(indent=2))

{
  "dataset_name": "spesa",
  "column_name": "rata",
  "expected_pattern": "YYYYMM",
  "semantic_hint": "temporal_period",
  "target_dtype": "Int64",
  "target_role": "code",
  "dominant_shape": "999999",
  "dominant_example_values": [
    "202402",
    "202406",
    "202408",
    "202404",
    "202410"
  ],
  "example_inconsistent_values": [
    "Rata 2024",
    "2024-02",
    "2024-04",
    "2024-09",
    "2024-08",
    "2024-10",
    "2024-01",
    "2024-05",
    "2023-12",
    "2024-03",
    "2024-07",
    "08/2024",
    "12/2023",
    "2024-06",
    "GIU-2024",
    "03/2024",
    "07/2024",
    "09/2024",
    "MAR-2024",
    "02/2024",
    "10/2024",
    "04/2024",
    "AGO-2024",
    "APR-2024",
    "DIC-2023",
    "FEB-2024",
    "GEN-2024",
    "LUG-2024",
    "05/2024",
    "SET-2024",
    "01/2024",
    "06/2024",
    "OTT-2024",
    "Rata 2023",
    "MAG-2024"
  ],
  "suggested_strategy": "Target format: 'YYYYMM'. Dominant valid shape: '999999' — values matching this shape are already valid, preserve them. \nExamples of already-valid values (the OUTPUT must look exactly like these): '202402', '202406', '202408', '202404', '202410'.\n\nHandle every outlier shape group below by inferring the transformation from the examples. For each group, verify your transformation produces output that matches the already-valid examples above — same length, same character structure, same field order (e.g. YYYY before MM, not MM before YYYY). Use partial matches, prefix stripping, abbreviation expansion, or abbreviation mapping as needed. Map to null ONLY when a value is completely unrecognisable — never null a value that contains recoverable information:\n\n  shape '9999-99': e.g. '2024-02', '2024-04', '2024-09', '2024-08', '2024-10'\n  shape '99/9999': e.g. '08/2024', '12/2023', '03/2024', '07/2024', '09/2024'\n  shape 'AAA-9999': e.g. 'GIU-2024', 'MAR-2024', 'AGO-2024', 'APR-2024', 'DIC-2023'\n  shape 'AAAA 9999': e.g. 'Rata 2024', 'Rata 2023'\n\nEVERY value in example_inconsistent_values must be explicitly handled — do not leave any outlier value unchanged unless it already matches the target format. Prefer a best-effort conversion over null whenever the value contains recoverable information."
}

### 8.2 Host-side validator — what can go wrong

The validator emits one of these `CleanerValidationIssue` categories. None require an LLM — they are pure Python checks against the generated code.

| Category | Meaning |
|---|---|
| `program_mismatch` | Program declares a different column name than the request. |
| `non_self_contained_function` | Cleaner references outer-scope names (NameError on load or call). |
| `runtime_exception` | Cleaner raised any other exception. |
| `shadowed_specific_branch` | Generic `if '<sep>' in s:` above a more specific branch on the same separator. |
| `dominant_value_modified` | Cleaner rewrote an already-valid dominant example — identity violation. |
| `outlier_unchanged` | Cleaner returned an inconsistent example unchanged. |
| `wrong_output_shape` | Output value shape does not match the dominant output shape. |
| `not_parseable_as_target_dtype` | Cleaned value does not parse as `Int64` / `Float64` / `datetime64[ns]` / `boolean`. |
| `not_matching_target_pattern` | Cleaned value does not match the numeric schema pattern (e.g. `YYYYMM`). |

### 8.3 The per-column loop

Below is the **real, executing source** of `run_column_cleaner_program` — displayed via `inspect.getsource`. Progress reporting (stderr prints + optional UI callback) is encapsulated in a `_GenerationProgress` object so the control flow reads cleanly.

In [26]:
from cleaning.generation import run_column_cleaner_program, GENERATOR_USAGE_LIMITS, _stagnation_temperature
print(f"GENERATOR_USAGE_LIMITS = {GENERATOR_USAGE_LIMITS}")
print(f"stagnation ramp 0..5: {[round(_stagnation_temperature(n), 2) for n in range(1, 6)]}")
print()
print(inspect.getsource(run_column_cleaner_program))

GENERATOR_USAGE_LIMITS = UsageLimits(tool_calls_limit=1)
stagnation ramp 0..5: [0.2, 0.3, 0.4, 0.5, 0.5]

def run_column_cleaner_program(
    dataset_name: str,
    request: ColumnCleaningRequest,
    max_attempts: int = 10,
    on_event: ProgressCallback | None = None,
) -> ColumnCleanerProgram:
    """Generator / critic / host-validator loop for a single column.

    Per attempt:
      1. Build the generator prompt (with failure context + optional stagnation brief).
      2. Ask the generator agent for a self-contained cleaner program.
      3. Validate the program host-side (no LLM).
      4. If valid, return the verified program.
      5. Otherwise: detect stagnation, invoke the critic, feed its diagnosis forward.
    """
    progress = _make_progress(on_event)
    previous_program: ColumnCleanerProgram | None = None
    validation_issues: list[CleanerValidationIssue] = []
    repair_diagnosis: CleanerRepairDiagnosis | None = None
    last_fingerprint: tuple[str, ...] | None = None
    consecutive_stagnant = 0

    for attempt in range(1, max_attempts + 1):
        stagnation = consecutive_stagnant >= 1
        progress.attempt_start(request.column_name, attempt, max_attempts, stagnation)

        prompt = _build_cleaner_generation_prompt(
            dataset_name, request,
            previous_program=previous_program,
            validation_issues=validation_issues,
            repair_diagnosis=repair_diagnosis,
            attempt_number=attempt,
            stagnation_detected=stagnation,
        )
        model_settings = {"temperature": _stagnation_temperature(consecutive_stagnant)} if stagnation else None
        try:
            program = run_agent_with_backoff(
                column_cleaner_generator_agent, prompt,
                usage_limits=GENERATOR_USAGE_LIMITS,
                model_settings=model_settings,
            ).output
        except UsageLimitExceeded as error:
            raise ValueError(
                "Generator exceeded the one-code-execution limit. "
                "This prevents hidden self-repair loops; simplify the prompt or raise the explicit limit if needed."
            ) from error

        validation_issues = validate_generated_cleaner_program(request, program)
        if not validation_issues:
            progress.generator_accepted(request.column_name, attempt)
            return rebuild_verified_program(request, program)
        progress.validation_failed(request.column_name, attempt, max_attempts, validation_issues[0])

        fingerprint = validation_issue_fingerprint(validation_issues)
        same_code = previous_program is not None and program.python_code.strip() == previous_program.python_code.strip()
        repeated_failure = last_fingerprint is not None and fingerprint == last_fingerprint
        if same_code or repeated_failure:
            reason = "repeated the same code" if same_code else "repeated the same host-side failures"
            progress.stagnation_noted(request.column_name, attempt, max_attempts, reason)
            consecutive_stagnant += 1
        else:
            consecutive_stagnant = 0
        previous_program, last_fingerprint = program, fingerprint

        if attempt < max_attempts:
            progress.critic_started(request.column_name, len(validation_issues))
            repair_diagnosis = run_cleaner_repair_critic(dataset_name, request, program, validation_issues)
            progress.critic_diagnosis(request.column_name, repair_diagnosis)
            if not repair_diagnosis.should_retry:
                failure_lines = "\n".join(f"- {format_validation_issue(issue)}" for issue in validation_issues[:10])
                raise ValueError(
                    f"Cleaner generation stopped for column '{request.column_name}' because the critic advised against retrying: "
                    f"{repair_diagnosis.root_cause}\n{failure_lines}"
                )

    failure_lines = "\n".join(f"- {format_validation_issue(issue)}" for issue in validation_issues[:10])
    raise ValueError(
        f"Cleaner generation failed local validation for column '{request.column_name}' after {max_attempts} attempts:\n"
        f"{failure_lines}"
    )

### 8.4 Generate one cleaner per inconsistent column

`run_cleaner_generation` drives the loop over every format-consistency finding, saves each accepted program to `Data/.cleaning_cache/<dataset>/generated_cleaners/<column>.py`, and writes `cleaner_manifest.json`.

In [27]:
from cleaning.generation import run_cleaner_generation  # driver: generator/critic loop per column
artifacts = run_cleaner_generation(DATASET_PATH, reuse_consistency=True, max_attempts=10)
for a in artifacts:
    print(f"- {a.column_name}  ->  {a.code_path}")
    print(f"    {a.summary}")

11:56:45.942 column-cleaner-generator run
11:56:45.944   chat gpt-4o-mini

[generate] 'rata' - 35 outlier examples -> sandbox...
[orchestrator][generator] column='rata' attempt=1/10
[orchestrator][generator] column='rata' accepted on attempt 1
  saved: C:\Users\sebas\Documents\GitHub\AgentsAI\Data\.cleaning_cache\spesa\generated_cleaners\rata.py
  sandbox validation (40 transformations):

  ORIGINAL                            CLEANED                             RATIONALE
  ----------------------------------- ----------------------------------- ------------------------------
  '202402'                            '202402'                            Preserved already-valid example during host verification.
  '202406'                            '202406'                            Preserved already-valid example during host verification.
  '202408'                            '202408'                            Preserved already-valid example during host verification.
  '202404'                            '202404'                            Preserved already-valid example during host verification.
  '202410'                            '202410'                            Preserved already-valid example during host verification.
  'Rata 2024'                         '202401'                            Converted during host-side verification of the accepted cleaner.
  '2024-02'                           '202402'                            Converted during host-side verification of the accepted cleaner.
  '2024-04'                           '202404'                            Converted during host-side verification of the accepted cleaner.
  '2024-09'                           '202409'                            Converted during host-side verification of the accepted cleaner.
  '2024-08'                           '202408'                            Converted during host-side verification of the accepted cleaner.
  '2024-10'                           '202410'                            Converted during host-side verification of the accepted cleaner.
  '2024-01'                           '202401'                            Converted during host-side verification of the accepted cleaner.
  '2024-05'                           '202405'                            Converted during host-side verification of the accepted cleaner.
  '2023-12'                           '202312'                            Converted during host-side verification of the accepted cleaner.
  '2024-03'                           '202403'                            Converted during host-side verification of the accepted cleaner.
  '2024-07'                           '202407'                            Converted during host-side verification of the accepted cleaner.
  '08/2024'                           '202408'                            Converted during host-side verification of the accepted cleaner.
  '12/2023'                           '202312'                            Converted during host-side verification of the accepted cleaner.
  '2024-06'                           '202406'                            Converted during host-side verification of the accepted cleaner.
  'GIU-2024'                          '202406'                            Converted during host-side verification of the accepted cleaner.
  '03/2024'                           '202403'                            Converted during host-side verification of the accepted cleaner.
  '07/2024'                           '202407'                            Converted during host-side verification of the accepted cleaner.
  '09/2024'                           '202409'                            Converted during host-side verification of the accepted cleaner.
  'MAR-2024'                          '202403'                            Converted during host-side verification of the accepted cleaner.
  '02/2024'                           '202402'                            Converted during host-side verification of the accepted cleaner.
  '10/2024'                           '202410'                            Converted during host-side verification of the accepted cleaner.
  '04/2024'                           '202404'                            Converted during host-side verification of the accepted cleaner.
  'AGO-2024'                          '202408'                            Converted during host-side verification of the accepted cleaner.
  'APR-2024'                          '202404'                            Converted during host-side verification of the accepted cleaner.
  'DIC-2023'                          '202312'                            Converted during host-side verification of the accepted cleaner.
  'FEB-2024'                          '202402'                            Converted during host-side verification of the accepted cleaner.
  'GEN-2024'                          '202401'                            Converted during host-side verification of the accepted cleaner.
  'LUG-2024'                          '202407'                            Converted during host-side verification of the accepted cleaner.
  '05/2024'                           '202405'                            Converted during host-side verification of the accepted cleaner.
  'SET-2024'                          '202409'                            Converted during host-side verification of the accepted cleaner.
  '01/2024'                           '202401'                            Converted during host-side verification of the accepted cleaner.
  '06/2024'                           '202406'                            Converted during host-side verification of the accepted cleaner.
  'OTT-2024'                          '202410'                            Converted during host-side verification of the accepted cleaner.
  'Rata 2023'                         '202301'                            Converted during host-side verification of the accepted cleaner.
  'MAG-2024'                          '202405'                            Converted during host-side verification of the accepted cleaner.

[generate] 'spesa' - 60 outlier examples -> sandbox...
[orchestrator][generator] column='spesa' attempt=1/10

11:57:24.034 column-cleaner-generator run
11:57:24.035   chat gpt-4o-mini

[orchestrator][generator] column='spesa' accepted on attempt 1
  saved: C:\Users\sebas\Documents\GitHub\AgentsAI\Data\.cleaning_cache\spesa\generated_cleaners\spesa.py
  sandbox validation (65 transformations):

  ORIGINAL                            CLEANED                             RATIONALE
  ----------------------------------- ----------------------------------- ------------------------------
  '182904.47999999954'                '182904.47999999954'                Preserved already-valid example during host verification.
  '2110811.34'                        '2110811.34'                        Preserved already-valid example during host verification.
  '732614.36'                         '732614.36'                         Preserved already-valid example during host verification.
  '43365008.73'                       '43365008.73'                       Preserved already-valid example during host verification.
  '1310915.22'                        '1310915.22'                        Preserved already-valid example during host verification.
  '713512,58'                         '713512.58'                         Converted during host-side verification of the accepted cleaner.
  '724.1800000000001 EUR'             '724.1800000000001'                 Converted during host-side verification of the accepted cleaner.
  '€2302425.16'                       '2302425.16'                        Converted during host-side verification of the accepted cleaner.
  '10071.580000000007 EUR'            '10071.580000000007'                Converted during host-side verification of the accepted cleaner.
  '101568,5'                          '101568.5'                          Converted during host-side verification of the accepted cleaner.
  '10639.539999999999 EUR'            '10639.539999999999'                Converted during host-side verification of the accepted cleaner.
  '110.38999999999999 EUR'            '110.38999999999999'                Converted during host-side verification of the accepted cleaner.
  '12650.6 EUR'                       '12650.6'                           Converted during host-side verification of the accepted cleaner.
  '133805,1'                          '133805.1'                          Converted during host-side verification of the accepted cleaner.
  '134453,87'                         '134453.87'                         Converted during host-side verification of the accepted cleaner.
  '135945.27 EUR'                     '135945.27'                         Converted during host-side verification of the accepted cleaner.
  '13892,9'                           '13892.9'                           Converted during host-side verification of the accepted cleaner.
  '14749.169999999998 EUR'            '14749.169999999998'                Converted during host-side verification of the accepted cleaner.
  '1478602,75'                        '1478602.75'                        Converted during host-side verification of the accepted cleaner.
  '151268,06'                         '151268.06'                         Converted during host-side verification of the accepted cleaner.
  '16.85 EUR'                         '16.85'                             Converted during host-side verification of the accepted cleaner.
  '171133661.04 EUR'                  '171133661.04'                      Converted during host-side verification of the accepted cleaner.
  '1746.8200000000004 EUR'            '1746.8200000000004'                Converted during host-side verification of the accepted cleaner.
  '1770527.74 EUR'                    '1770527.74'                        Converted during host-side verification of the accepted cleaner.
  '182.12 EUR'                        '182.12'                            Converted during host-side verification of the accepted cleaner.
  '19161.11 EUR'                      '19161.11'                          Converted during host-side verification of the accepted cleaner.
  '19721001,6'                        '19721001.6'                        Converted during host-side verification of the accepted cleaner.
  '1982561,9899999935'                '1982561.9899999935'                Converted during host-side verification of the accepted cleaner.
  '2048.3000000000006 EUR'            '2048.3000000000006'                Converted during host-side verification of the accepted cleaner.
  '20548.35000000001 EUR'             '20548.35000000001'                 Converted during host-side verification of the accepted cleaner.
  '211856,67'                         '211856.67'                         Converted during host-side verification of the accepted cleaner.
  '215.09 EUR'                        '215.09'                            Converted during host-side verification of the accepted cleaner.
  '22011,35'                          '22011.35'                          Converted during host-side verification of the accepted cleaner.
  '2308,62'                           '2308.62'                           Converted during host-side verification of the accepted cleaner.
  '23451,880000000026'                '23451.880000000026'                Converted during host-side verification of the accepted cleaner.
  '2376290.27 EUR'                    '2376290.27'                        Converted during host-side verification of the accepted cleaner.
  '24620,419999999976'                '24620.419999999976'                Converted during host-side verification of the accepted cleaner.
  '252.85999999999999 EUR'            '252.85999999999999'                Converted during host-side verification of the accepted cleaner.
  '25458,13'                          '25458.13'                          Converted during host-side verification of the accepted cleaner.
  '263,22'                            '263.22'                            Converted during host-side verification of the accepted cleaner.
  '26370151.900012985 EUR'            '26370151.900012985'                Converted during host-side verification of the accepted cleaner.
  '27263.25 EUR'                      '27263.25'                          Converted during host-side verification of the accepted cleaner.
  '275273.9 EUR'                      '275273.9'                          Converted during host-side verification of the accepted cleaner.
  '285791.47 EUR'                     '285791.47'                         Converted during host-side verification of the accepted cleaner.
  '2910.4299999999994 EUR'            '2910.4299999999994'                Converted during host-side verification of the accepted cleaner.
  '31248,250000000073'                '31248.250000000073'                Converted during host-side verification of the accepted cleaner.
  '3136,5899999999874'                '3136.5899999999874'                Converted during host-side verification of the accepted cleaner.
  '315,02000000000004'                '315.02000000000004'                Converted during host-side verification of the accepted cleaner.
  '3157355.42 EUR'                    '3157355.42'                        Converted during host-side verification of the accepted cleaner.
  '31988,720000000372'                '31988.720000000372'                Converted during host-side verification of the accepted cleaner.
  '3220974.08 EUR'                    '3220974.08'                        Converted during host-side verification of the accepted cleaner.
  '326336.05 EUR'                     '326336.05'                         Converted during host-side verification of the accepted cleaner.
  '33,73'                             '33.73'                             Converted during host-side verification of the accepted cleaner.
  '344,28000000000003'                '344.28000000000003'                Converted during host-side verification of the accepted cleaner.
  '3447739.18 EUR'                    '3447739.18'                        Converted during host-side verification of the accepted cleaner.
  '3474.38 EUR'                       '3474.38'                           Converted during host-side verification of the accepted cleaner.
  '3576919,67'                        '3576919.67'                        Converted during host-side verification of the accepted cleaner.
  '3632.610000000002 EUR'             '3632.610000000002'                 Converted during host-side verification of the accepted cleaner.
  '3652.220000000001 EUR'             '3652.220000000001'                 Converted during host-side verification of the accepted cleaner.
  '386,69999999999993'                '386.69999999999993'                Converted during host-side verification of the accepted cleaner.
  '39614.34000000002 EUR'             '39614.34000000002'                 Converted during host-side verification of the accepted cleaner.
  '4034494.029999837 EUR'             '4034494.029999837'                 Converted during host-side verification of the accepted cleaner.
  '4073052.72 EUR'                    '4073052.72'                        Converted during host-side verification of the accepted cleaner.
  '412.58 EUR'                        '412.58'                            Converted during host-side verification of the accepted cleaner.
  '41360.020000000026 EUR'            '41360.020000000026'                Converted during host-side verification of the accepted cleaner.

[generate] 'aggregation-time' - 50 outlier examples -> sandbox...
[orchestrator][generator] column='aggregation-time' attempt=1/10

11:58:35.777 column-cleaner-generator run
11:58:35.779   chat gpt-4o-mini

[orchestrator][generator] column='aggregation-time' accepted on attempt 1
  saved: C:\Users\sebas\Documents\GitHub\AgentsAI\Data\.cleaning_cache\spesa\generated_cleaners\aggregation_time.py
  sandbox validation (55 transformations):

  ORIGINAL                            CLEANED                             RATIONALE
  ----------------------------------- ----------------------------------- ------------------------------
  '2024-03-11T02:01:04.421'           '2024-03-11T02:01:04.421'           Preserved already-valid example during host verification.
  '2024-07-11T03:01:16.866'           '2024-07-11T03:01:16.866'           Preserved already-valid example during host verification.
  '2024-09-11T03:01:11.704'           '2024-09-11T03:01:11.704'           Preserved already-valid example during host verification.
  '2024-05-11T03:01:07.269'           '2024-05-11T03:01:07.269'           Preserved already-valid example during host verification.
  '2024-11-11T02:00:28.485'           '2024-11-11T02:00:28.485'           Preserved already-valid example during host verification.
  '11/01/2024'                        '2024-01-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11/07/2024'                        '2024-07-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11/05/2024'                        '2024-05-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '24/10/2024'                        '2024-10-24T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11/11/2024'                        '2024-11-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11/02/2024'                        '2024-02-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11/03/2024'                        '2024-03-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11/04/2024'                        '2024-04-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '16/08/2024'                        '2024-08-16T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11/06/2024'                        '2024-06-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11-11-24'                          '2024-11-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '24-10-24'                          '2024-10-24T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11-06-24'                          '2024-06-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11-02-24'                          '2024-02-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11-05-24'                          '2024-05-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11-09-24'                          '2024-09-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11-01-24'                          '2024-01-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11-07-24'                          '2024-07-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '16-08-24'                          '2024-08-16T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11-03-24'                          '2024-03-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '2024/06/11'                        '2024-06-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '2024/10/24'                        '2024-10-24T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '2024/04/11'                        '2024-04-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '2024/07/11'                        '2024-07-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '2024/02/11'                        '2024-02-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '2024/03/11'                        '2024-03-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '2024/09/11'                        '2024-09-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '2024/08/16'                        '2024-08-16T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '2024/01/11'                        '2024-01-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '2024/11/11'                        '2024-11-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11.05.2024'                        '2024-05-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11.11.2024'                        '2024-11-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11.02.2024'                        '2024-02-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11.01.2024'                        '2024-01-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11.06.2024'                        '2024-06-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '16.08.2024'                        '2024-08-16T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '24.10.2024'                        '2024-10-24T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11.04.2024'                        '2024-04-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11.07.2024'                        '2024-07-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  '11.09.2024'                        '2024-09-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  'GIU 11 2024'                       '2024-06-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  'APR 11 2024'                       '2024-04-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  'LUG 11 2024'                       '2024-07-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  'MAG 11 2024'                       '2024-05-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  'OTT 24 2024'                       '2024-10-24T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  'GEN 11 2024'                       '2024-01-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  'MAR 11 2024'                       '2024-03-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  'NOV 11 2024'                       '2024-11-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  'SET 11 2024'                       '2024-09-11T00:00:00.000'           Converted during host-side verification of the accepted cleaner.
  'AGO 16 2024'                       '2024-08-16T00:00:00.000'           Converted during host-side verification of the accepted cleaner.

[generate] 'SPESA TOTALE' - 60 outlier examples -> sandbox...
[orchestrator][generator] column='SPESA TOTALE' attempt=1/10

12:01:19.796 column-cleaner-generator run
12:01:19.798   chat gpt-4o-mini
- rata  ->  C:\Users\sebas\Documents\GitHub\AgentsAI\Data\.cleaning_cache\spesa\generated_cleaners\rata.py
    Host validation passed: preserved 5 dominant examples and converted 35 inconsistent examples.
- spesa  ->  C:\Users\sebas\Documents\GitHub\AgentsAI\Data\.cleaning_cache\spesa\generated_cleaners\spesa.py
    Host validation passed: preserved 5 dominant examples and converted 60 inconsistent examples.
- aggregation-time  ->  C:\Users\sebas\Documents\GitHub\AgentsAI\Data\.cleaning_cache\spesa\generated_cleaners\aggregation_time.py
    Host validation passed: preserved 5 dominant examples and converted 50 inconsistent examples.
- SPESA TOTALE  ->  C:\Users\sebas\Documents\GitHub\AgentsAI\Data\.cleaning_cache\spesa\generated_cleaners\spesa_totale.py
    Host validation passed: preserved 5 dominant examples and converted 60 inconsistent examples.

[orchestrator][generator] column='SPESA TOTALE' accepted on attempt 1
  saved: C:\Users\sebas\Documents\GitHub\AgentsAI\Data\.cleaning_cache\spesa\generated_cleaners\spesa_totale.py
  sandbox validation (65 transformations):

  ORIGINAL                            CLEANED                             RATIONALE
  ----------------------------------- ----------------------------------- ------------------------------
  '182904.47999999954'                '182904.47999999954'                Preserved already-valid example during host verification.
  '2110811.34'                        '2110811.34'                        Preserved already-valid example during host verification.
  '732614.36'                         '732614.36'                         Preserved already-valid example during host verification.
  '43365008.73'                       '43365008.73'                       Preserved already-valid example during host verification.
  '1310915.22'                        '1310915.22'                        Preserved already-valid example during host verification.
  '713512,58'                         '713512.58'                         Converted during host-side verification of the accepted cleaner.
  '724.1800000000001 EUR'             '724.1800000000001'                 Converted during host-side verification of the accepted cleaner.
  '€2302425.16'                       '2302425.16'                        Converted during host-side verification of the accepted cleaner.
  '10071.580000000007 EUR'            '10071.580000000007'                Converted during host-side verification of the accepted cleaner.
  '101568,5'                          '101568.5'                          Converted during host-side verification of the accepted cleaner.
  '10639.539999999999 EUR'            '10639.539999999999'                Converted during host-side verification of the accepted cleaner.
  '110.38999999999999 EUR'            '110.38999999999999'                Converted during host-side verification of the accepted cleaner.
  '12650.6 EUR'                       '12650.6'                           Converted during host-side verification of the accepted cleaner.
  '133805,1'                          '133805.1'                          Converted during host-side verification of the accepted cleaner.
  '134453,87'                         '134453.87'                         Converted during host-side verification of the accepted cleaner.
  '135945.27 EUR'                     '135945.27'                         Converted during host-side verification of the accepted cleaner.
  '13892,9'                           '13892.9'                           Converted during host-side verification of the accepted cleaner.
  '14749.169999999998 EUR'            '14749.169999999998'                Converted during host-side verification of the accepted cleaner.
  '1478602,75'                        '1478602.75'                        Converted during host-side verification of the accepted cleaner.
  '151268,06'                         '151268.06'                         Converted during host-side verification of the accepted cleaner.
  '16.85 EUR'                         '16.85'                             Converted during host-side verification of the accepted cleaner.
  '171133661.04 EUR'                  '171133661.04'                      Converted during host-side verification of the accepted cleaner.
  '1746.8200000000004 EUR'            '1746.8200000000004'                Converted during host-side verification of the accepted cleaner.
  '1770527.74 EUR'                    '1770527.74'                        Converted during host-side verification of the accepted cleaner.
  '182.12 EUR'                        '182.12'                            Converted during host-side verification of the accepted cleaner.
  '19161.11 EUR'                      '19161.11'                          Converted during host-side verification of the accepted cleaner.
  '19721001,6'                        '19721001.6'                        Converted during host-side verification of the accepted cleaner.
  '1982561,9899999935'                '1982561.9899999935'                Converted during host-side verification of the accepted cleaner.
  '2048.3000000000006 EUR'            '2048.3000000000006'                Converted during host-side verification of the accepted cleaner.
  '20548.35000000001 EUR'             '20548.35000000001'                 Converted during host-side verification of the accepted cleaner.
  '211856,67'                         '211856.67'                         Converted during host-side verification of the accepted cleaner.
  '215.09 EUR'                        '215.09'                            Converted during host-side verification of the accepted cleaner.
  '22011,35'                          '22011.35'                          Converted during host-side verification of the accepted cleaner.
  '2308,62'                           '2308.62'                           Converted during host-side verification of the accepted cleaner.
  '23451,880000000026'                '23451.880000000026'                Converted during host-side verification of the accepted cleaner.
  '2376290.27 EUR'                    '2376290.27'                        Converted during host-side verification of the accepted cleaner.
  '24620,419999999976'                '24620.419999999976'                Converted during host-side verification of the accepted cleaner.
  '252.85999999999999 EUR'            '252.85999999999999'                Converted during host-side verification of the accepted cleaner.
  '25458,13'                          '25458.13'                          Converted during host-side verification of the accepted cleaner.
  '263,22'                            '263.22'                            Converted during host-side verification of the accepted cleaner.
  '26370151.900012985 EUR'            '26370151.900012985'                Converted during host-side verification of the accepted cleaner.
  '27263.25 EUR'                      '27263.25'                          Converted during host-side verification of the accepted cleaner.
  '275273.9 EUR'                      '275273.9'                          Converted during host-side verification of the accepted cleaner.
  '285791.47 EUR'                     '285791.47'                         Converted during host-side verification of the accepted cleaner.
  '2910.4299999999994 EUR'            '2910.4299999999994'                Converted during host-side verification of the accepted cleaner.
  '31248,250000000073'                '31248.250000000073'                Converted during host-side verification of the accepted cleaner.
  '3136,5899999999874'                '3136.5899999999874'                Converted during host-side verification of the accepted cleaner.
  '315,02000000000004'                '315.02000000000004'                Converted during host-side verification of the accepted cleaner.
  '3157355.42 EUR'                    '3157355.42'                        Converted during host-side verification of the accepted cleaner.
  '31988,720000000372'                '31988.720000000372'                Converted during host-side verification of the accepted cleaner.
  '3220974.08 EUR'                    '3220974.08'                        Converted during host-side verification of the accepted cleaner.
  '326336.05 EUR'                     '326336.05'                         Converted during host-side verification of the accepted cleaner.
  '33,73'                             '33.73'                             Converted during host-side verification of the accepted cleaner.
  '344,28000000000003'                '344.28000000000003'                Converted during host-side verification of the accepted cleaner.
  '3447739.18 EUR'                    '3447739.18'                        Converted during host-side verification of the accepted cleaner.
  '3474.38 EUR'                       '3474.38'                           Converted during host-side verification of the accepted cleaner.
  '3576919,67'                        '3576919.67'                        Converted during host-side verification of the accepted cleaner.
  '3632.610000000002 EUR'             '3632.610000000002'                 Converted during host-side verification of the accepted cleaner.
  '3652.220000000001 EUR'             '3652.220000000001'                 Converted during host-side verification of the accepted cleaner.
  '386,69999999999993'                '386.69999999999993'                Converted during host-side verification of the accepted cleaner.
  '39614.34000000002 EUR'             '39614.34000000002'                 Converted during host-side verification of the accepted cleaner.
  '4034494.029999837 EUR'             '4034494.029999837'                 Converted during host-side verification of the accepted cleaner.
  '4073052.72 EUR'                    '4073052.72'                        Converted during host-side verification of the accepted cleaner.
  '412.58 EUR'                        '412.58'                            Converted during host-side verification of the accepted cleaner.
  '41360.020000000026 EUR'            '41360.020000000026'                Converted during host-side verification of the accepted cleaner.

[generate] manifest saved -> C:\Users\sebas\Documents\GitHub\AgentsAI\Data\.cleaning_cache\spesa\cleaner_manifest.json

### 8.5 Inspect one generated cleaner (from disk)

The generator's output is written to disk as a regular `.py` file. That is the cleaner that will be executed in the apply stage.

In [28]:
if artifacts:
    cleaner_src = Path(artifacts[0].code_path).read_text(encoding="utf-8")
    print(f"# {artifacts[0].code_path}\n")
    print(cleaner_src)

# C:\Users\sebas\Documents\GitHub\AgentsAI\Data\.cleaning_cache\spesa\generated_cleaners\rata.py

def clean_rata(value):
    import re

    if value is None or str(value).strip() == '':
        return None
    s = str(value).strip()

    # First preserve already-valid values using structural patterns derived from dominant examples.
    canonical_examples = ['202402', '202406', '202408', '202404', '202410']
    def _structural_regex(example):
        parts, cursor = [], 0
        for match in re.finditer(r'\d+', example):
            start, end = match.span()
            if start > cursor:
                parts.append(re.escape(example[cursor:start]))
            parts.append(r'\d{' + str(end - start) + '}')
            cursor = end
        if cursor < len(example):
            parts.append(re.escape(example[cursor:]))
        return '^' + ''.join(parts) + '$'

    canonical_patterns = [_structural_regex(e) for e in canonical_examples if e and e != '...']
    if any(re.fullmatch(pattern, s) for pattern in canonical_patterns):
        return s

    # Handle outlier formats as shape-specific branches.
    m = re.fullmatch(r'(\d{4})-(\d{2})', s)
    if m:
        year, month = m.groups()
        return f"{year}{month.zfill(2)}"

    m = re.fullmatch(r'(\d{2})/(\d{4})', s)
    if m:
        month, year = m.groups()
        return f"{year}{month.zfill(2)}"

    m = re.fullmatch(r'([A-Za-z]{3})-(\d{4})', s)
    if m:
        month_abbr, year = m.groups()
        month_map = {
            'GEN': '01', 'FEB': '02', 'MAR': '03', 'APR': '04',
            'MAG': '05', 'GIU': '06', 'LUG': '07', 'AGO': '08',
            'SET': '09', 'OTT': '10', 'NOV': '11', 'DIC': '12'
        }
        month = month_map.get(month_abbr.upper())
        if month:
            return f"{year}{month}"

    m = re.fullmatch(r'Rata (\d{4})', s)
    if m:
        year = m.group(1)
        return f"{year}01"  # Defaulting to January for "Rata"

    return None

### 8.6 Apply the remediation plan + generated cleaners

Actions are applied in a fixed, safe order:

1. Column renames (from schema suggestions)
2. Placeholder → null replacements (from completeness findings)
3. Generated per-column cleaners (from this section)
4. Exact duplicate column drops
5. Explicit dtype casts

The cleaned CSV is written to `Data/.cleaning_cache/<dataset>/<dataset>.cleaned.csv`.

In [29]:
from cleaning.application import run_cleaner_application_with_plan  # applies renames + nulls + cleaners + casts
cleaning_report, execution_reports, applied_plan = run_cleaner_application_with_plan(DATASET_PATH, remediation_plan)
print(cleaning_report.summary)
if execution_reports:
    display(pd.DataFrame([r.model_dump(exclude={"sample_updates"}) for r in execution_reports]))

[apply] step 1 - format cleaners (4 columns)
  'rata' OK - 510 rows changed
  'spesa' OK - 238 rows changed
  'aggregation-time' OK - 602 rows changed
  'SPESA TOTALE' OK - 232 rows changed

  execution summary: 4/4 succeeded

[apply] step 2 - placeholder -> null (from completeness cache)
  'ente': 111 placeholder values -> null
  'descrizione': 178 placeholder values -> null
  'cod_imposta': 91 placeholder values -> null
  'imposta': 131 placeholder values -> null
  total placeholder replacements: 511

[apply] step 3 - exact duplicate column drops (from remediation plan)
  dropped exact duplicate column 'cod imposta ext' (kept '2cod_imposta')

[apply] step 4 - column renames (from schema cache)
  'Tipo Imposta' -> 'tipo_imposta_2' (suffixed - base name already exists)
  'aggregation-time' -> 'aggregation_time'
  'Tipo Imposta' -> 'tipo_imposta_2'
  'SPESA TOTALE' -> 'spesa_totale'
  '2cod_imposta' -> 'cod_imposta_2'
  'ente%code' -> 'ente_code'

[apply] step 5 - dtype casting (from schema cache)
  '_id' -> string
  'rata' -> Int64
  'ente' -> Int64
  'descrizione' -> string

Applied 4 format cleaners, replaced 511 placeholder values, renamed 5 columns, and cast dtypes. Cleaned dataset saved to `C:/Users/sebas/Documents/GitHub/AgentsAI/Data/.cleaning_cache/spesa/spesa.cleaned.csv`.

  'cod_tipoimposta' -> Int64
  'tipo_imposta' -> string
  'cod_imposta' -> Int64
  'imposta' -> string
  'spesa' -> Float64
  'aggregation_time' -> datetime64[ns]
  'area_geografica' -> string
  'note' -> string
  'fonte_dato' -> string
  'spesa_totale' -> Float64
  'cod_imposta_2' -> Int64
  'ente_code' -> Int64
  16 columns cast successfully, 0 skipped.

[apply] cleaned dataset saved -> C:\Users\sebas\Documents\GitHub\AgentsAI\Data\.cleaning_cache\spesa\spesa.cleaned.csv

,column_name,function_name,execution_ok,changed_rows,unresolved_risks,summary
0,rata,clean_rata,True,510,[],Applied successfully: 510 rows changed.
1,spesa,clean_spesa,True,238,[],Applied successfully: 238 rows changed.
2,aggregation-time,clean_aggregation_time,True,602,[],Applied successfully: 602 rows changed.
3,SPESA TOTALE,clean_SPESA_TOTALE,True,232,[],Applied successfully: 232 rows changed.

### 8.7 Verification — before vs. after

`run_verify` re-runs the format-consistency validation on the cleaned CSV (read as raw strings so pandas cannot silently re-normalise formats) and produces a per-column `FindingDiff` with status `resolved` / `improved` / `unchanged` / `regressed` / `new`.

In [30]:
from cleaning.verification import run_verify  # re-runs consistency on the cleaned CSV
verification_report = run_verify(DATASET_PATH)
print(verification_report.summary)
pd.DataFrame([d.model_dump() for d in verification_report.diffs])

[verify] running consistency on cleaned dataset: C:\Users\sebas\Documents\GitHub\AgentsAI\Data\.cleaning_cache\spesa\spesa.cleaned.csv

4 resolved (rata, spesa, aggregation-time→aggregation_time, SPESA TOTALE→spesa_totale)

[verify] diff - 4 original findings -> 0 remaining

  COLUMN            STATUS        BEFORE     AFTER   REDUCTION
  ----------------  ----------  --------  --------  ----------
  rata              resolved         510         0      100.0%
  spesa             resolved         168         0      100.0%
  aggregation-time  resolved         602         0      100.0%
  SPESA TOTALE      resolved         168         0      100.0%

,column_name,status,before_inconsistent_rows,after_inconsistent_rows,reduction_pct,remaining_examples,renamed_to
0,rata,resolved,510,0,100.0,[],None
1,spesa,resolved,168,0,100.0,[],None
2,aggregation-time,resolved,602,0,100.0,[],aggregation_time
3,SPESA TOTALE,resolved,168,0,100.0,[],spesa_totale

## 9. Final report + narrative

The pipeline's closing act: merge every artifact into a `FinalPipelineReport`, write it to `<dataset>.final_report.json`, then invoke `narrative_report_agent` to produce a professional Markdown report for human review.

In [31]:
from cleaning.reporting import (
    build_final_report,            # pure model merge, no LLM
    save_final_report,             # writes final_report.json
    generate_narrative_report,     # calls narrative_report_agent
    save_narrative_report,         # writes narrative_report.md
)

final_report = build_final_report(
    validation_results,
    applied_plan,
    cleaning_report,
    verification_report,
    dataset_path=DATASET_PATH,
)
save_final_report(DATASET_PATH, final_report)
narrative = generate_narrative_report(final_report)
narrative_path = save_narrative_report(DATASET_PATH, narrative)
display(Markdown(narrative_path.read_text(encoding="utf-8")))

12:03:04.576 narrative-report run
12:03:04.578   chat gpt-4o-mini

# NarrativeReport

The dataset 'spesa' comprises 7543 rows and underwent extensive quality checks revealing a total of 79 findings across various categories. The overall quality posture indicates that 30 remediation actions were successfully applied, while 57 actions were proposed for manual review. Key findings included 8 schema issues, 9 completeness concerns, 4 format inconsistencies, 3 anomalies, and 6 cross-column checks. Notably, 4 format inconsistencies were resolved, including renaming columns and correcting data types. No unresolved risks remain, indicating a thorough cleaning process. The cleaned output is saved at `C:/Users/sebas/Documents/GitHub/AgentsAI/Data/.cleaning_cache/spesa/spesa.cleaned.csv`.

## Dataset Overview

The dataset 'spesa' consists of a total of 7543 rows and originally contained multiple columns, which were reduced after cleaning. The cleaning process identified a total of 79 findings, leading to 30 remediation actions applied. Of these, 57 actions were deferred for manual review, ensuring that any complex issues are addressed by a data steward. The cleaned output file can be found at `C:/Users/sebas/Documents/GitHub/AgentsAI/Data/.cleaning_cache/spesa/spesa.cleaned.csv`. The overall quality posture reflects a significant effort to enhance the dataset's integrity, with a focus on schema validation, completeness, format consistency, anomaly detection, and cross-column checks.

## Schema Validation

### Column Renames
| Original Name | New Name | Reason |
|---------------|----------|--------|
| 2cod_imposta | cod_imposta_2 | Column name contains a leading digit, violating the lowercase snake_case naming rule. |
| aggregation-time | aggregation_time | Column name contains a hyphen, violating the lowercase snake_case naming rule. |
| ente%code | ente_code | Column name contains a percent sign, violating the lowercase snake_case naming rule. |
| SPESA TOTALE | spesa_totale | Column name contains uppercase letters and whitespace, violating the lowercase snake_case naming rule. |
| Tipo Imposta | tipo_imposta_2 | Column name contains uppercase letters and whitespace, violating the lowercase snake_case naming rule. |

### Type Casts
| Column | Assigned Type | % Non-Null |
|--------|---------------|-------------|
| rata | Int64 | 100.0% |
| spesa | Float64 | 99.1% |
| aggregation_time | datetime64[ns] | 100.0% |
| spesa_totale | Float64 | 99.2% |
| ente | Int64 | 96.0% |
| descrizione | string | 94.8% |
| cod_imposta | Int64 | 97.0% |
| imposta | string | 96.1% |
| area_geografica | string | 79.0% |
| note | string | 2.0% |
| fonte_dato | string | 1.0% |
| tipo_imposta | string | 100.0% |
| cod_tipoimposta | Int64 | 100.0% |
| cod_imposta_2 | Int64 | 100.0% |
| ente_code | Int64 | 100.0% |
| _id | string | 100.0% |

Planned casts that were marked as not needed included 'cod_imposta_ext' and 'tipo_imposta_2', as they were already in the desired format.

## Completeness Analysis

The completeness analysis identified several columns with placeholder values that were replaced with nulls. The following table summarizes the findings:

| Column Name | Placeholder Count | Tokens Detected | Completeness % |
|--------------|------------------|-----------------|-----------------|
| ente | 282 | ['unknown', '', '//', '?', 'n.d.'] | 96.26143444252949% |
| descrizione | 422 | ['n.d.', '?', '//', '', '-'] | 94.40540898846614% |
| cod_imposta | 206 | ['n.d.', '', '-', '//', '?'] | 97.26899111759248% |
| imposta | 340 | ['-', '//', '', 'unknown', '?'] | 95.49250961156038% |
| spesa | 59 | ['N.D.'] | 99.21781784435902% |
| area_geografica | 1582 | [''] | 79.02691236908393% |
| note | 7393 | [''] | 1.9885987007821821% |
| fonte_dato | 7468 | [''] | 0.9942993503910911% |
| SPESA TOTALE | 59 | ['N.D.'] | 99.21781784435902% |

Columns such as 'area_geografica', 'note', and 'fonte_dato' had significant placeholder values, indicating a need for further review. However, the planned replacements for 'spesa' and 'spesa_totale' were marked as not needed since they were already compliant.

## Format Consistency

A total of 4 columns had format inconsistencies that were addressed. The following details outline the specific columns affected:

### rata
- **Expected Pattern:** YYYYMM
- **Inconsistent Rows:** 510
- **Examples of bad values:** 'Rata 2024', '2024-02', '2024-04', '2024-09', '2024-08', '2024-10'
- **Transformation applied:** Cleaned to conform to YYYYMM format.
- **Clean example:** 'Rata 2024' → '202401'
- **Outcome:** Fixed

### spesa
- **Expected Pattern:** decimal number
- **Inconsistent Rows:** 168
- **Examples of bad values:** '713512,58', '724.1800000000001 EUR', '€2302425.16', '10071.580000000007 EUR', '101568,5', '10639.539999999999 EUR'
- **Transformation applied:** Cleaned to decimal number format.
- **Clean example:** '713512,58' → '713512.58'
- **Outcome:** Fixed

### aggregation_time
- **Expected Pattern:** ISO 8601 datetime
- **Inconsistent Rows:** 602
- **Examples of bad values:** '11/01/2024', '11/07/2024', '11/05/2024', '24/10/2024', '11/11/2024', '11/02/2024'
- **Transformation applied:** Cleaned to ISO 8601 datetime format.
- **Clean example:** '11/01/2024' → '2024-01-11T00:00:00.000'
- **Outcome:** Fixed

### SPESA TOTALE
- **Expected Pattern:** decimal number
- **Inconsistent Rows:** 168
- **Examples of bad values:** '713512,58', '724.1800000000001 EUR', '€2302425.16', '10071.580000000007 EUR', '101568,5', '10639.539999999999 EUR'
- **Transformation applied:** Cleaned to decimal number format.
- **Clean example:** '713512,58' → '713512.58'
- **Outcome:** Fixed

All identified inconsistencies were resolved, leading to a significant improvement in data quality.

## Anomaly Detection

The anomaly detection process identified several significant issues:
- **Numeric Outlier in 'spesa':**
  - **Severity:** High
  - **Affected Rows:** 1101
  - **Example Values:** '43365008.73', '7639226.66', '3887279.49', '9518447.34', '10455819.51', '87912478.86'
  - **Evidence:** 1101 rows fall outside the robust IQR band [-1879828.180, 2512978.350] computed from Q1=2803.190, Q3=630346.980.
  - **Suggested Action:** Review whether these values are genuine extreme cases or unit/format errors before imputation or removal.

- **Numeric Outlier in 'SPESA TOTALE':**
  - **Severity:** High
  - **Affected Rows:** 1098
  - **Example Values:** '43365008.73', '7639226.66', '3887279.49', '9518447.34', '10455819.51', '87912478.86'
  - **Evidence:** 1098 rows fall outside the robust IQR band [-1868763.280, 2498349.960] computed from Q1=2856.680, Q3=626730.000.
  - **Suggested Action:** Review whether these values are genuine extreme cases or unit/format errors before imputation or removal.

- **Rare Category in 'tipo_imposta':**
  - **Severity:** Low
  - **Affected Rows:** 6
  - **Example Values:** 'ERARIALI', 'erariali', 'Da definire', 'Mista'
  - **Evidence:** 4 rare categories occur at or below 37 row(s) each out of 7543 non-null values.
  - **Suggested Action:** Review whether these rare labels are valid edge cases, spelling variants, or categories that should be consolidated.

Each flagged item was routed to manual review rather than auto-corrected to ensure accurate handling of potential data integrity issues.

## Cross-Column Checks

The cross-column checks revealed several significant findings:

### Exact Duplicate Columns
No exact duplicate columns were detected.

### Near-Duplicate Columns
- **spesa & SPESA TOTALE:**
  - **Severity:** Medium
  - **Affected Rows:** 7484
  - **Similarity %:** 99.48

- **cod_imposta & 2cod_imposta:**
  - **Severity:** Medium
  - **Affected Rows:** 7337
  - **Similarity %:** 99.74

- **cod_imposta & cod imposta ext:**
  - **Severity:** Medium
  - **Affected Rows:** 7337
  - **Similarity %:** 99.74

- **ente & ente%code:**
  - **Severity:** Medium
  - **Affected Rows:** 7261
  - **Similarity %:** 99.72

### Semantic Conflicts
- **tipo_imposta & Tipo Imposta:**
  - **Severity:** High
  - **Affected Rows:** 385

These findings indicate the need for further review to determine whether any columns can be consolidated or require separate handling.

## Row Duplicate Analysis

The row duplicate analysis identified a total of 49 duplicate groups, affecting 98 rows. The key columns used for identifying duplicates include '_id', 'rata', 'ente', 'descrizione', 'cod_tipoimposta', 'tipo_imposta', 'cod_imposta', 'imposta', 'spesa', 'aggregation-time', 'area_geografica', 'note', 'fonte_dato', 'Tipo Imposta', 'SPESA TOTALE', '2cod_imposta', 'cod imposta ext', 'ente%code'. Examples of exact duplicate groups include:
- Group 1: Rows [128, 6521]
- Group 2: Rows [155, 6659]
- Group 3: Rows [315, 912]

Exact duplicates were not auto-removed due to a conservative policy to maintain data lineage. Near-duplicates require manual review to determine if they represent valid variations or errors.

## Remediation Action Summary

The remediation actions applied to the dataset are summarized as follows:
- **Applied:** 30
- **Deferred:** 57
- **Failed:** 0
- **Not Needed:** 8

### Breakdown by Action Type
| Action Type | Applied | Deferred | Failed | Not Needed |
|-------------|---------|----------|--------|------------|
| cast_dtype | 16 | 0 | 0 | 2 |
| drop_exact_duplicate_column | 1 | 0 | 0 | 0 |
| generate_cleaner | 4 | 0 | 0 | 0 |
| rename_column | 5 | 0 | 0 | 0 |
| replace_placeholders_with_null | 4 | 0 | 0 | 6 |

The auto-apply policy allows for automatic application of actions that are straightforward and do not require human judgment, such as type casting and renaming columns. However, actions that involve potential data integrity issues, such as dropping duplicates or resolving semantic conflicts, are deferred for manual review.

## Verification Outcome

The verification process confirmed the resolution of 4 format inconsistencies:
- **rata (renamed from RATA):** Fixed
- **spesa:** Fixed
- **aggregation_time (renamed from aggregation-time):** Fixed
- **spesa_totale (renamed from SPESA TOTALE):** Fixed

The verification results indicate that all identified inconsistencies were resolved, leading to a significant improvement in data quality. The following table summarizes the verification outcomes:

| Column Name | Before Status | After Status |
|-------------|---------------|--------------|
| rata | 510 | 0 | Fixed |
| spesa | 168 | 0 | Fixed |
| aggregation_time | 602 | 0 | Fixed |
| spesa_totale | 168 | 0 | Fixed |

This indicates that the cleaning process was effective in addressing the identified issues.

## Residual Risks & Manual Review Queue

No unresolved risks from the cleaning process remain. All identified issues have been addressed, and the manual review queue includes the following items:
- **Near-Duplicate Columns:** Review the columns 'spesa' and 'SPESA TOTALE' for potential consolidation.
- **Semantic Conflicts:** Review the columns 'tipo_imposta' and 'Tipo Imposta' for potential reconciliation.
- **Near-Duplicate Rows:** Review identified near-duplicate rows for resolution.
- **Numeric Outliers:** Review the flagged outliers in 'spesa' and 'SPESA TOTALE' for potential imputation or removal.
- **Proposed Actions:** 57 actions proposed for manual review require human judgment.

Overall, the dataset has undergone a thorough cleaning process, and no residual risks remain.

## Raccomandazioni

1. Conduct a manual review of near-duplicate columns to determine if any can be consolidated.
2. Resolve the semantic conflict between 'tipo_imposta' and 'Tipo Imposta' to ensure data consistency.
3. Review flagged numeric outliers in 'spesa' and 'SPESA TOTALE' to assess their validity.
4. Implement a process for regularly updating and maintaining the dataset to prevent future inconsistencies.
5. Consider automating the review process for near-duplicate rows to streamline future data cleaning efforts.

## 10. Closing

Everything produced by this run lives under the dataset's parent directory:

```
Data/.validation_cache/spesa.*.json         # schema, completeness, consistency, anomaly, cross_column, duplicates, remediation_plan, validation_bundle
Data/.cleaning_cache/spesa/
    generated_cleaners/*.py                  # one Python cleaner per inconsistent column
    cleaner_manifest.json                    # list of GeneratedCleanerArtifact
    spesa.cleaned.csv                        # fully cleaned dataset
    spesa.final_report.json                  # FinalPipelineReport serialised
    spesa.narrative_report.md                # the document rendered above
```

Re-running the notebook reuses every cached validation artifact (instant) except the cleaning half, which regenerates cleaners each time since their path in the notebook passes no reuse flag. For deeper internals, see `docs/AGENT_ARCHITECTURE.md` and `docs/REMEDIATION_WORKFLOW.md`.